---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/homerun2-sops-secrets.enc.yaml
  - flux-system/minio-secrets.enc.yaml
  - flux-system/openbao-sops-secrets.enc.yaml
  - flux-system/tabletennis-sops-secrets.enc.yaml
