apiVersion: ENC[AES256_GCM,data:6yQ=,iv:nMwkx9KI+AIhGGje2ab2i4YaAJrpFC7JC0L+3PabebM=,tag:3UsRcG1SdM/+DaFDQt7LlA==,type:str]
kind: ENC[AES256_GCM,data:Beb8CX6y,iv:TBC+Two5Dvco4BmHHQhEbKG1nP1bzsVg1rPfEBocJ9o=,tag:huo0tSUK0JhNtjAF9tz+5g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Ndndppkm9Oz1RbUL1wE=,iv:szRZYldewqW2rA8Mqk5to4BiwFtrulfB32tPRO4nAzI=,tag:qS0LhsecJcFZ/a3kQB26Xw==,type:str]
    namespace: ENC[AES256_GCM,data:nUoj9xESw4MPEgE=,iv:P9DH926eu/ImJ43rPHA2iWb4Ze5XPQ7FA5k0LxoPlmA=,tag:+OwC/csISUlkK3iEnAbxXw==,type:str]
type: ENC[AES256_GCM,data:O0NKr7XW,iv:bDFNovL3MzgaGvDLWOdmNRd1SKodlbrxdnzv4Zu6gV8=,tag:RWazpTOWeEhru8w3ThhpfQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:cb8+sWOyFReqc5MRFUSvvrhr6Q==,iv:w/sN9oK1yzoPaA6RUYBtkOL7E31wUGakgwp16+/Jsj0=,tag:L0xcDVvlz5sadKGzdWIl3w==,type:str]
    password: ENC[AES256_GCM,data:Ou0c1yM3US1VZiDiwQkLIXmYC+5+Cvv6fmIpzc0fuO8McUMZQsHglg==,iv:TD+g6tRDU4wy/mBEarbTOIZifvucHHNxFOCsiyY1SMs=,tag:q8wbXqB4rN2MAQb4qUuykA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWDZ3aVppL3YvQWdhdi94
            Q0xBU0FkVitLbEsxSzhFajgvNG9XM1hkaDNVClU3NHR3SmxIL2xYY0lPODFMZVdo
            Y3B1cStUT2hmek1QZ2RnekRUMUNqenMKLS0tIFFGc3U1cU1Va3hxNjFERS82dUFz
            VmtlcC9xQ1hVSWVkU3hXdGZiOVhxM2sKCz/oxnJzaSn4GbFdhUtXRlCPx2VnIjY0
            bsusJq13ZWK0jPedoHjAdEKvspzkLJ3RKa6wq404QYKrYL2/UtrcQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
    lastmodified: "2026-09-17T08:19:53Z"
    mac: ENC[AES256_GCM,data:j54y2tELVWxTzA9vS9ktP9noqQqd4oiW/rEZJAbqBylA43KJaIb7ec1XUri4QoDNra2EOfBECngXEgwaU9n0YA7TU7WlioTZpaC/C3HqzQ0z6un2UK97T86pefL6HNqQQX8tqQRqUiFd1E7GIjsUVqWA1miLr6e7Da9Of/tqlSM=,iv:aToOKJbAeHMLqk3ghJJGN2PyNxxrWLiTK2avxD0mnUI=,tag:pA34/Mm9d1c29Si/NlK7bw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
---
apiVersion: ENC[AES256_GCM,data:TTA=,iv:xvfoXAOeNesz608GMwu6fy4hzK/QYYfT0FoA3gBT6iE=,tag:J0Y7iquEs+UVlrsWEDhf4w==,type:str]
kind: ENC[AES256_GCM,data:HiY3x+5m,iv:awdKC2p6kmye4cZ9tzjwmmy037oiuZm8oBp2kfiwp0U=,tag:MsPSLwcuZHHEdFNCTj51cQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:fL2abB0ZiGM=,iv:/fTrVZMmTl8CzdwOoXaZ2vcHP0MCVALc5NPfX3DK8aU=,tag:RGYqB6JsCf9h6dYI7/v1TQ==,type:str]
    namespace: ENC[AES256_GCM,data:PPfYdsbn55ziwAw=,iv:E1cQaNhUKCkm2YMNMrRf/otIyGT+v3KTNmHSlmWzO98=,tag:5szOjNNrOcP0Wx7GQdpkIQ==,type:str]
type: ENC[AES256_GCM,data:n9oHHE/6,iv:6tM0KfwBSvOFqdVcvy2aGyMTHlAyQRQrRKfmmlhUHTo=,tag:srrt23PyiM7F6PfAs0QUTQ==,type:str]
stringData:
    age.agekey: ENC[AES256_GCM,data:ejJ/vEUBoXefeHbwh57R4uyDbpW26bHyhButq5giYao1uDun1uuU72Ih3IGyvb0cMCScPV5rFXXizGajXigTqCTb3m5vfQH54K0=,iv:ZmNfvPnBTqJW0qtHmzlJgW5OD+FwTP8jYbMaa6ofsy0=,tag:9ZUxWXlyw8CGndEbgdZwtg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWDZ3aVppL3YvQWdhdi94
            Q0xBU0FkVitLbEsxSzhFajgvNG9XM1hkaDNVClU3NHR3SmxIL2xYY0lPODFMZVdo
            Y3B1cStUT2hmek1QZ2RnekRUMUNqenMKLS0tIFFGc3U1cU1Va3hxNjFERS82dUFz
            VmtlcC9xQ1hVSWVkU3hXdGZiOVhxM2sKCz/oxnJzaSn4GbFdhUtXRlCPx2VnIjY0
            bsusJq13ZWK0jPedoHjAdEKvspzkLJ3RKa6wq404QYKrYL2/UtrcQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
    lastmodified: "2026-09-17T08:19:53Z"
    mac: ENC[AES256_GCM,data:j54y2tELVWxTzA9vS9ktP9noqQqd4oiW/rEZJAbqBylA43KJaIb7ec1XUri4QoDNra2EOfBECngXEgwaU9n0YA7TU7WlioTZpaC/C3HqzQ0z6un2UK97T86pefL6HNqQQX8tqQRqUiFd1E7GIjsUVqWA1miLr6e7Da9Of/tqlSM=,iv:aToOKJbAeHMLqk3ghJJGN2PyNxxrWLiTK2avxD0mnUI=,tag:pA34/Mm9d1c29Si/NlK7bw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
