apiVersion: ENC[AES256_GCM,data:TTA=,iv:xvfoXAOeNesz608GMwu6fy4hzK/QYYfT0FoA3gBT6iE=,tag:J0Y7iquEs+UVlrsWEDhf4w==,type:str]
kind: ENC[AES256_GCM,data:HiY3x+5m,iv:awdKC2p6kmye4cZ9tzjwmmy037oiuZm8oBp2kfiwp0U=,tag:MsPSLwcuZHHEdFNCTj51cQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Ndndppkm9Oz1RbUL1wE=,iv:szRZYldewqW2rA8Mqk5to4BiwFtrulfB32tPRO4nAzI=,tag:qS0LhsecJcFZ/a3kQB26Xw==,type:str]
    namespace: ENC[AES256_GCM,data:PPfYdsbn55ziwAw=,iv:E1cQaNhUKCkm2YMNMrRf/otIyGT+v3KTNmHSlmWzO98=,tag:5szOjNNrOcP0Wx7GQdpkIQ==,type:str]
type: ENC[AES256_GCM,data:n9oHHE/6,iv:6tM0KfwBSvOFqdVcvy2aGyMTHlAyQRQrRKfmmlhUHTo=,tag:srrt23PyiM7F6PfAs0QUTQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:cb8+sWOyFReqc5MRFUSvvrhr6Q==,iv:w/sN9oK1yzoPaA6RUYBtkOL7E31wUGakgwp16+/Jsj0=,tag:L0xcDVvlz5sadKGzdWIl3w==,type:str]
    password: ENC[AES256_GCM,data:x1WCySwOAF8ednk10P1fEnnvyQrJSb0U+Ea+1rPTQblUX7+LInGW/Q==,iv:Jry+ZK4OOusTb15QCgyZ/rQb6Y9Gnu/0AE4Fq4CDNy8=,tag:BMc9AB5XvnFQG8fe7iDd6Q==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWDZ3aVppL3YvQWdhdi94
            Q0xBU0FkVitLbEsxSzhFajgvNG9XM1hkaDNVClU3NHR3SmxIL2xYY0lPODFMZVdo
            Y3B1cStUT2hmek1QZ2RnekRUMUNqenMKLS0tIFFGc3U1cU1Va3hxNjFERS82dUFz
            VmtlcC9xQ1hVSWVkU3hXdGZiOVhxM2sKCz/oxnJzaSn4GbFdhUtXRlCPx2VnIjY0
            bsusJq13ZWK0jPedoHjAdEKvspzkLJ3RKa6wq404QYKrYL2/UtrcQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-21T12:02:43Z"
    mac: ENC[AES256_GCM,data:Zqi/Q/BOz3XngNb/whXzBIj35mqRu//TdbbgNkfmvkcePr2Ckm4Vuhc/vv25LCXliGBg3YykFcp0sK9BPGHUL8yqR/PZhbOEj2PDZ74VssJiH6xYPJ02OrPj6D+A/avnwYe3YbDFyIF9VVBq/uLI4y9URA5ccXEH1yVi/Gi77tA=,iv:H7Das3PaaekmJXc5xVVsBuq5ssu7lrEi/avrbVnMjNo=,tag:HG0+ZfSwoLfWVnXsGcEn0A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
---
apiVersion: ENC[AES256_GCM,data:TTA=,iv:xvfoXAOeNesz608GMwu6fy4hzK/QYYfT0FoA3gBT6iE=,tag:J0Y7iquEs+UVlrsWEDhf4w==,type:str]
kind: ENC[AES256_GCM,data:HiY3x+5m,iv:awdKC2p6kmye4cZ9tzjwmmy037oiuZm8oBp2kfiwp0U=,tag:MsPSLwcuZHHEdFNCTj51cQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:fL2abB0ZiGM=,iv:/fTrVZMmTl8CzdwOoXaZ2vcHP0MCVALc5NPfX3DK8aU=,tag:RGYqB6JsCf9h6dYI7/v1TQ==,type:str]
    namespace: ENC[AES256_GCM,data:PPfYdsbn55ziwAw=,iv:E1cQaNhUKCkm2YMNMrRf/otIyGT+v3KTNmHSlmWzO98=,tag:5szOjNNrOcP0Wx7GQdpkIQ==,type:str]
type: ENC[AES256_GCM,data:n9oHHE/6,iv:6tM0KfwBSvOFqdVcvy2aGyMTHlAyQRQrRKfmmlhUHTo=,tag:srrt23PyiM7F6PfAs0QUTQ==,type:str]
stringData:
    age.agekey: ENC[AES256_GCM,data:ejJ/vEUBoXefeHbwh57R4uyDbpW26bHyhButq5giYao1uDun1uuU72Ih3IGyvb0cMCScPV5rFXXizGajXigTqCTb3m5vfQH54K0=,iv:ZmNfvPnBTqJW0qtHmzlJgW5OD+FwTP8jYbMaa6ofsy0=,tag:9ZUxWXlyw8CGndEbgdZwtg==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWDZ3aVppL3YvQWdhdi94
            Q0xBU0FkVitLbEsxSzhFajgvNG9XM1hkaDNVClU3NHR3SmxIL2xYY0lPODFMZVdo
            Y3B1cStUT2hmek1QZ2RnekRUMUNqenMKLS0tIFFGc3U1cU1Va3hxNjFERS82dUFz
            VmtlcC9xQ1hVSWVkU3hXdGZiOVhxM2sKCz/oxnJzaSn4GbFdhUtXRlCPx2VnIjY0
            bsusJq13ZWK0jPedoHjAdEKvspzkLJ3RKa6wq404QYKrYL2/UtrcQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-21T12:02:43Z"
    mac: ENC[AES256_GCM,data:Zqi/Q/BOz3XngNb/whXzBIj35mqRu//TdbbgNkfmvkcePr2Ckm4Vuhc/vv25LCXliGBg3YykFcp0sK9BPGHUL8yqR/PZhbOEj2PDZ74VssJiH6xYPJ02OrPj6D+A/avnwYe3YbDFyIF9VVBq/uLI4y9URA5ccXEH1yVi/Gi77tA=,iv:H7Das3PaaekmJXc5xVVsBuq5ssu7lrEi/avrbVnMjNo=,tag:HG0+ZfSwoLfWVnXsGcEn0A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
