apiVersion: ENC[AES256_GCM,data:AQ8=,iv:N7fOYZN8Ki1qrjSC0wqg8py1UQQHmAxVRCl+KqBXZQE=,tag:dOtbGDkUPb3A6FGb8vBOzw==,type:str]
kind: ENC[AES256_GCM,data:HT14A366,iv:KKGfZBx/iK5xRdeaEzwuS61ineOKNtr79Ang4dxeHOg=,tag:HL5Edd2h6NOfLN8mvGTGuw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6mFcL76Ytc7zz0blOKA=,iv:ApjWfxY9e+Z8snCwkEIxNexbK/r0cngyrwfI6fEO8to=,tag:Zh66HAhpQJREvwLXHvvxNQ==,type:str]
    namespace: ENC[AES256_GCM,data:YOQJvHDWMNYwym0=,iv:5rb86rQvFbVsLGissGYUTN0RMm/SBp8tAEvGnzPdktw=,tag:jItfHCF48cyO74JkN+P1TQ==,type:str]
type: ENC[AES256_GCM,data:md4S8APM,iv:9j7Juzp2HorT+PsXJc8p1lm+xC+Qv3CAldaEhF//qJc=,tag:CyDgQ3D4UxGeuZgn2cjMWA==,type:str]
stringData:
    ARGO_CD_SERVER_ADMIN_PASSWORD: ENC[AES256_GCM,data:QzSfqePtTT63MSwqR2uMwpkBbI6qWK2pFmbEbZHDVN5GMKDLmvXKpxwMAx2oaMTBHsmBSLjLP31SclN+,iv:UIYuLwmqww2u0W0xw1rVwk1iy+V/oqRORCEXCOSoosc=,tag:1MmXb9cnS+ZL60D7oD3vOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSHplNGd5aFdGTVV1NDVm
            K2ptMVFFU0ROVXJlMnNKMVdYaWthSys2c1hnCk5iWTZ4ME55bGk1SjRTejdWMTBv
            TGFobUVBeTVWWUllOWdSQzFCSDNOWlEKLS0tIEoyNjJ0dG1WaTY3MDh3SXNrd054
            NG45N0xxU0t5SW9zVU5Db282Z0hOWTAKXF6mNMZfQVWEyTxSEQ+egUD2vzu1dTmD
            VWtWeMjucM9sJiFWEj87qi9qRu5tVvxQRWCZ6p+jifx/ROcR+QpW9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-05T08:36:48Z"
    mac: ENC[AES256_GCM,data:yMDH4M4YqbXUPTL1JJYVjAyOOMyg3iGHoGC1KT0jsJ0fpdCNcJu586dcwcTBoriJH3fMEoPrbdRicDoySsrnWlQxLljt1q/5Hx/YeSnB/v5QxlZdSUR/bJLzI8GqziDK/VjO9i7/cBAO3z4wluCOiiohK0GgFgwqXSsjlSCZP3g=,iv:HXe0GJBo651RTIgMmAxl3dGF3O/D3RNUZ/2qE/25gtk=,tag:CMSYVI9EzEw5rBsEkiD1yQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
