#ENC[AES256_GCM,data:6LQKT0nABdJ+/YQYT6iZigQY1t8gg9Hr/dh6buO//lRUcnqoH6hGHFqZ6MIc3fqs2uI4tCEVJeBYrgtQYqijo7Vt8bFOkG6GdLApXR2zcFk=,iv:qYjeY2f9wFadvmhgDbvXlEIoZTx4OfY+Sorrpshr/iM=,tag:+SP+eJKoelLTSNbkMSZsUw==,type:comment]
#
#ENC[AES256_GCM,data:/QN7AirhCyrsM33Gz95lZmkC+vKUCLqhtu5RtuoFgjE83RVObAcBMhaIeyZgsDGID1yBVeA3ZVveVX/8tayvCAOIKoKvVnpv,iv:oTiaztxpAuwvHk+fSHsi/NqwJZDmZ0Qryn8boSjIsB8=,tag:uBU8U2prxtS/luA0H1X/hg==,type:comment]
#ENC[AES256_GCM,data:gtNV7ukXKoSn/ly+uDG0UKI0G4y73jtqK3/GDkTA6RVLDDZmgOZTfd3Hp3MXhnJY1xQjuwYKFaIPegbTMNw7VxnrHK+LbyMLSMJ3JHRIlA==,iv:dwTnNo/+2efjvzaX3w/ux75AIfTKynpOLQjHmJUDhvA=,tag:LyF20d6Y53Eh5vqJdOu7Jw==,type:comment]
#ENC[AES256_GCM,data:MRWNWsZEBmIn1j09jtEgpngkPUUNDkAkl7/l7daiSTz1qqlHVivTd048nlSKmOAeVBqfr+x9G8So1jTLaC/56nRVXIsmx6Nu2BEg,iv:haB3S0KZKMZGixp7GWECoBrkI3uztXAYEV33I6jb8LY=,tag:DhCEdgD9mhUJeEHtbiovpw==,type:comment]
#ENC[AES256_GCM,data:I0BMAAIj37Q/BQjlpf6zENMhdNkW69JyaV5nWJ0lY0ZNtfdDmSuy9huDcVjWB+9FoW5FPF5OUnXM3y9w9paHywSMkQArBfMwJKzA3/w=,iv:sSs+xEXMuoizssHjUF0jpFtQwcTGnosog4EuBjbS7Jg=,tag:3UnOSO8ecKhDmKkrWVB8Zw==,type:comment]
#ENC[AES256_GCM,data:iEwpyMXXKZ9EW1JLJw==,iv:XsH1iyo7bXfuWf+ntUU7kewqst2Ax0Xy/bgSZiB7gtA=,tag:wmR9gS7/ApOQ4TJTd5NzJQ==,type:comment]
#
#ENC[AES256_GCM,data:2G6uHD+w7J8ys9OYyltWIu67Y+I=,iv:y9Z1G3SoiI42fb8BLocfyt9kXolAqQ8r/CfZVaL1XxE=,tag:MJ4Tdzxe/aAu4QEFKFWcEw==,type:comment]
#
#ENC[AES256_GCM,data:BCl4MtExrxu9MqVpACacdQ3XDbBk5DpDvyFAyNCb2SGufti1Wtsa9xw61tUKsmcr8YfBOjWUKzeZ/JlpQtwDqd12Ng==,iv:j4iG4Opg9zV+2gVPmWKdfuPZx4OGKOsEwRedPe23SdI=,tag:xNakDzII6yO07zONBABkfw==,type:comment]
#
#ENC[AES256_GCM,data:GJpbbOy9Gzc97zZg6QCtDspVPvccHSCkphrsYsqbhf0jdkYGGFHJUP1C7c6S11F3cbhO5QRkYvD5PyZ7usYs0WZ6IH/C5Z336KTNHec=,iv:rcwbdHDtb8XrHlaGUJqTwmxh5k9TzgblLxw8YsQZqFM=,tag:D8eh6gbFe29wVYFX5JNuqw==,type:comment]
#ENC[AES256_GCM,data:8EzXpHAMjWHT+gwCSOkU74awx8jXFFNeIrdK4X5al6MgIEafB32yyZfWwVSgb1rEoWTJmcYbZ9j0v84TMRxOPjqbkfowCRAxFoQ=,iv:Ww7vDp919mUxMHbTsXW+Nr+X2Zi3so8OBh2bPYOmkP8=,tag:9fUDMznhPhJ+uKGtNNX+bA==,type:comment]
#ENC[AES256_GCM,data:hRUt+hlPixuqUlt/bdaVkUGv57pLi3qFJNADNkjYMoffZjNWCQxtRDiAwRxaeoLie7ho4kweK0TaeVRBZoJ1u7az+6RUXQ==,iv:m7y9cHlSrNn4Z1WBaKV9MREz3/SFAiYK1XGVT6C53ZY=,tag:cwnvTEFfGZEQLBJcLB81YA==,type:comment]
#ENC[AES256_GCM,data:kbuUfC1hoUZR6ULdERuaWE9c5BQSLOdMsqYNEyUQJV7/eoDADK2RF33735kAvjE3pwuJBC1iAk4IqA30bWxxkSUP0wLTJzC1A+sI1PbB,iv:nTQTT9zEkT0JX+Qygu8bD7DQsE1oUUGNuGLbcqdC81A=,tag:fUrTMp/iLtR6TZnNiwtTuA==,type:comment]
#ENC[AES256_GCM,data:EPKDJgQ60n70VFVsDNvf6E1ryez9bf9Gw5SU8bOD23zHg1TeRTrtUCrf9ZxWZpXbjyQ0z1KGllHzdu4F6X/IER5+A8UYvHuiH2pfvg==,iv:Xq1w1c8oX8XVf2cLQQ27AFarqijlAbCOfMX+zo7RQTU=,tag:7+3FSPpqBg5HNQ7Pv7oDYw==,type:comment]
#ENC[AES256_GCM,data:saIJHwlx+F8iXlcpwVC3RVcK/reKzQ==,iv:T4753dOsOdXS85NeN42OQAOwsdRiOy6b1lGn7EXt8Ns=,tag:CLF9xX1YPXH5m8UrrWpZoA==,type:comment]
apiVersion: ENC[AES256_GCM,data:pPw=,iv:6zIvfcM4m4JmMsHShbERK4fxWZkA36U5hIMxZ9mr5JY=,tag:KdQRUW+wfme7Ad2/vP1DXQ==,type:str]
kind: ENC[AES256_GCM,data:BfTtm9bj,iv:Gab7qgnIxt8RQ/ws7PzVnYdpP6Bnnk6dZ9+wbNQ0Egw=,tag:Y2q+ePsv8wiRryCaSOMxdw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:foaqw3y28G/EtdjXZcuTTKbb+I64l62PHGOq,iv:kWD2f7VI2SEd79Ny4Ly0X/mQ3zO45UkbCqAoLlxBDxM=,tag:azcbP6q18sFy8L8+vcdjLQ==,type:str]
    namespace: ENC[AES256_GCM,data:5OeBjOMJ,iv:r5ZScDU1DpVOI+yDgYUV2hnPGaJm4Fi5Oqccb0geo/s=,tag:E5xRjj6nQg52Rw3F7S2yGQ==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:GXHUQ4bRgA9EQr6xpngJYGR/BluQJqLiz647,iv:ReC+Rmay+MRCsKsGEiindJXhPKSGOD0G0iShC1FLX38=,tag:B55/L6Xld+2R7O4TdYHdQw==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:KAmTjX0G,iv:U6/zgY7x3msilQ+/TrQyyC3XFbw2ofWiP9W5N6TsbDo=,tag:hLjXwQT0Jr6kTyrRwoyKbQ==,type:str]
type: ENC[AES256_GCM,data:xSh/Vvje,iv:CtKV4uHhtBvQE4nIeg5t7D1p7FVi2bDJtV9JnElYLXw=,tag:UHYEavDYiRWsEH2NC4VpTw==,type:str]
stringData:
    teams-webhook-url: ENC[AES256_GCM,data:dE8COIOxBsoes994g6N6xv+JHCULwwa4sxkXeRuNy40W3VrI8Tmn1b00hth0ZT3STTERXSTO+uLmAyYNLpfp09q2Uw3t3miP7YEXfUTCZfyVZlc+OFZY8uvd1PmnGyEfNK5kN/wBtDNVr6I0W4f5Ke4RYdWXX7VEC4Ropcs1iZLU8eeviDRhQtsyvkrSHTDmF9/HXBUFIQxgms6Jcnc/QDsWq9xcJpqR/36izRjthahnrbY0uwSQUpwFoIKZN7uR+YosUS3q77WWhWvihPm0NJUwrqMzrAxgt1EkSAURKf42dCxFpwqZRnx5FIzkT29+AaJD02ilbFM0FaqEKyfxd0haCaZ2Q/J7DcW/4vysrfHTFsHL4Peu0338eqYAKgmeA3U=,iv:JVY7phrqAsvNF7DjRjoLnqKQaHul1YqXDxWuGn7NDOM=,tag:YX1ANA10iLxjjmZhlp9ujA==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOXRuRGt6Y0R2RFluZFhV
            WEliQ1J0YUtOU3hvMm1NSVVKSHd1ckFtYURnCmRIUVZKT0Vmd2Y2eUpnQXY2Y2ll
            MGEzcEwwTVo0djhPb0tHM05KM2pFNkUKLS0tIG9uWjJPWEhPRkZDQ2NBd0l1V2Ey
            N0RkUW5rY2FPWGRZTGtkeTZlN3B4aDgKRm17WhayrsyYtb4QQKFByHzHBblUWRwp
            9xAqFEHaTXJgUTpZKPV4a0FlE4W95V9ZHj2AqQDb4wkStFLRE+AtRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-14T12:25:30Z"
    mac: ENC[AES256_GCM,data:EtunOAqaik779x/qlN/NpvRk1EMV2/QWt2BmT43pAwFo2P2xs/RlyvaSoW6A1ddg/iBH3LQRmmZowDZcaBlyskrwYd4jlShJMRgk+QN95J9JNxp3uiA0IVramcyv6Em54u7p6ZAW3gDJ/MMx3GDfctSk4dpQud7s2hMq7qOg4oM=,iv:mLWekTXHRoZrz5JvzG4s7zTkoUUVRbAtSnZhETtYrwE=,tag:JlljUlPiYPnbwxmdFMRyBQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
