apiVersion: ENC[AES256_GCM,data:wo8=,iv:bezMC15kX63POx+AHTfwt+TDHI4oFLH3Nx1/OPrhUik=,tag:KAV5S0F0gMvsPfc6qvE/qQ==,type:str]
kind: ENC[AES256_GCM,data:1/vsWdKW,iv:gM2miCOo3zifAfSaq0eRUcI9WVf3dfLlnLLU2WcBFvg=,tag:1UsmKEEP7XJwZf863BBqGQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:olIidnXdo5g8X1/z5aAlzRdpbCX3APM=,iv:3e2rM4+JPSmsl81fdzTWkJV1dlqXB6HdURViKCRNgdE=,tag:4ofObJ5QRkcUiwrxR0x2Sg==,type:str]
    namespace: ENC[AES256_GCM,data:TtR3zQWtMlC86zI=,iv:Z4b529b1D/epuHjJZAe7IiXZYS5Mm7pg7yqcna+36BI=,tag:Cn/XucY+SFJFNRBHcN51wg==,type:str]
type: ENC[AES256_GCM,data:znvZv9qY,iv:bcxoi/j1+iVdpeNV+1n8jTCEK/ms62J86x9X8b6UguU=,tag:mBHCf/Mwmx094SCUMB9fwA==,type:str]
stringData:
    BACKSTAGE_GITHUB_TOKEN: ENC[AES256_GCM,data:VRZjNClMMTKuD67x1/hLyoDO+pGZhUkfi5za6UnReD4zbZsU6L6kpQ==,iv:E7wSHr9ab0dBC4xOvh3fQNiMhAlx9d61ZTG6fHENHIA=,tag:USE4MtYR6h0gvlpl/6JSfQ==,type:str]
    BACKSTAGE_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:kkmNStpK2lZ6zeFffrwrvUFiiAA=,iv:mBecWiCz/vHl+yyQxkSjqCYB5T89C7bdwtOpZ7Na2G0=,tag:rDBLUpS80SZSyUiqq5Ld1g==,type:str]
    BACKSTAGE_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:epFCdQuAbLa2f4ZG3g34V/cbncKNYkO5yP+elK1Y7TOerAbC0Mcjdg==,iv:tMFAWuyyCmy2s40/EFQ6ZOmyuMr2V92pQWAMpEdnwnI=,tag:DqnzIY44rKBI3lwOcmBH/A==,type:str]
    BACKSTAGE_BACKEND_SECRET: ENC[AES256_GCM,data:MRKfP1AQTRCaIy4qZPzjzxevLWQsZYYmiJXmksYNWhjV7ckMb0tTA0z2n+AW,iv:O+Bo+HCRbtq1Pc2TTKryorTdh119sScQ4XljT3gjJaQ=,tag:FLgD+2qPGOj1ouFAqWNGBw==,type:str]
    BACKSTAGE_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:09q8bItcKlo=,iv:ehCLnL9sM374rFFHBToHDuUEbfpMR5OYeDqxQVJpIiw=,tag:EfoPjEn+BuANEa/JYvEGQw==,type:str]
    BACKSTAGE_EXTERNAL_ACCESS_TOKEN: ENC[AES256_GCM,data:t4hCRMEzWFyt7Yk1bCGvvJTfxQPoJQKHxH/pZ3Tm4jg=,iv:gGU7G344k6+tL9dFw7RVxRNhxoEG0c4pU8W6Q2fKX40=,tag:gdZsJo/0PyrhNkAgvrMnjw==,type:str]
    BACKSTAGE_ZITADEL_ISSUER: ENC[AES256_GCM,data:uimhoc1DYE1HdUUkdgxvAy0XR8eaSGI80V1fg/GjxQHEFvcQHwSDCngNR3aUBIrgcHWm5LFHywib,iv:EQ1uZo6SoGp6s9jEXFXJ2Hk9FmPTV0AGUT7W+4Qlznk=,tag:EFX+xjAyFqje93rWcfO9MQ==,type:str]
    BACKSTAGE_ZITADEL_CLIENT_ID: ENC[AES256_GCM,data:bB4TPKnwff2drPjGDciUscHH,iv:fjST6w2a9cocD7kyEPAg+oQW4vNOWt11GwtF1O0Ty0s=,tag:vvw2/3rcIy2q+EONzr+hww==,type:str]
    BACKSTAGE_ZITADEL_CLIENT_SECRET: ENC[AES256_GCM,data:zUjxxj6qs3kokMq9H1tytGJxylMwsUK/zr3p+0qAwXQyaORHO8gxfq82JfYg74CHFjDzoTNup5LPxAKK2l8CKg==,iv:RQ0E6QmsaDFZW83w68TmI+g/D2iY0E8ryMd0aIVmW6E=,tag:0x6oS9HJFCAK3rp+gN7FDw==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYjhCYk5FYXNhNm9TYlpU
            b0dnbUNMSkxPeVNsY0FJSFBmT1hlQWppQ2hVCjUra0xzcGhJdWR5MFNxNkk5Rldh
            aW11cnNpZ3lqNThYcUtVLzNoV2NOV3cKLS0tIGpmWFRvaGVNQ1dMUHJFbU5NUDhx
            VkgybThXMkQ1S3hUcXQyNzhlTDE0ZkkK+I3NJoDHiJ/6+dHkdD6yJZnce9hFTw6A
            KizjaFTZ3AFPRcq4i6Uc5yQ5DqHwz5TROiWyZC6Fprlv/jUUxwMuXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-05T13:36:56Z"
    mac: ENC[AES256_GCM,data:5doq+RbS4easZMHDkTiz7Eax4tDhN/l2w22HomHNR3U+KFNHntv+imi0oLvcNMOtIxPMY9Jpu6nNNh1sXGRNRKo03dWWEtc2plngl2yNKK0wLhs/Ob3r07cysJA4kZNhd3qzJWQZSaOJp9D0lAZSVC/rSXfGO+dFgNdIq5VMaUY=,iv:GiQkvBTkuAUNq9uqKtthZuWGzrwgWLFDsUr5PwTHUKI=,tag:kiwUuVl81cJoSWJnhoIErA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
