apiVersion: ENC[AES256_GCM,data:+VM=,iv:yrPzFTh/BGI/8c4497Uu9SOqiQdiXU809ys4DaTz2YU=,tag:+cJD6hH/Bm1Ud+IHyM+uUA==,type:str]
kind: ENC[AES256_GCM,data:vRcbBmle,iv:z5euLI5HtMrN48VMHw6qAnpOt9LR8mx4hYDSNLgP9wY=,tag:5I8BNibItD5MjFhjG2Brvw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:iNzJnRB4Ejp/s3CPPwzIaYBLhnjzFQ==,iv:jmlZ5u8FUFpzJ84WGkze19znLMJ6PPQUVtp8wBRlX8Y=,tag:ifA8Ge9LFQmqYGtXmFCYtA==,type:str]
    namespace: ENC[AES256_GCM,data:QZgL1NLBleiGgyc=,iv:VliAzedl38mnBMJp1HRy6xHpRhF8eGxxs2R7GsPa1K8=,tag:luu7Nv0SrPj9/mQF+8p/IQ==,type:str]
type: ENC[AES256_GCM,data:Ey9W4IV3,iv:SxG8puY5L7Z1NTpK42JE9BMJbDAlmPzhJ79U26zgjGQ=,tag:sOhAf3G0MJcsBw87+yL2kg==,type:str]
stringData:
    DDWRT_PASSWORD: ENC[AES256_GCM,data:VmEu5gL1cSI=,iv:9CP/BqnAT9qZ+N01XKE2hVdld0l3PHf7qOQzcfzLz3Q=,tag:Dam1g/9SZ6yVHeJwkVLr0g==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4b2t3Z0hTRnByMG40V1hU
            ZE8rdXpmT3JaTnhHNVdkdzdaWVJ3NXMyV2dNCnNyK3paNDNqTHo2L3VTaUtGbmZj
            cjY2NzkzWE50NHBQUFNpa1phSUMvRFEKLS0tIDU4RTZLaGV0MVNQRHFJTkdOelJD
            U1pMQjlmcndvWTJ4M2gzZHhjQkgxWHcKkyMK7FaOyOZo71VO8Q4cIANF1Vlw05xR
            vrgyF70jmWzrLefjzvI/ZfCnNaJO/lpnRIM7L4U2LgJXyjrdd8SPNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T07:24:40Z"
    mac: ENC[AES256_GCM,data:86obXnjmS8x7GPy9FiazSK4znnQCzsmxmnyEbZnLmBV33IuTO1sr7NGz8ppL2ifSSDgtXdbIvkfcacn4wjr+k7Ao6pnbIAHxdo5ItmC7Z++1kjROGXpe00/+Pz+yOot44nvLENFLbJC07ELrtNfCpBJgwXS5WytYiTvFDMcgZ1I=,iv:2Hj+5f7C84CB5gymAeQjYXWGY5m+ZM39uWJCxiwxaiE=,tag:TeQn2fBl6xH85nkxzRz9Cg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
