apiVersion: ENC[AES256_GCM,data:6L8=,iv:+8RzcTjxgRM4+K66xxd5S/7Q3CaVWG07cZohFI2SNp8=,tag:jq7bemXKfGMBeCrTbdDjQA==,type:str]
kind: ENC[AES256_GCM,data:srrHKJlv,iv:39WUT7WPvBfPsLtgkmJEb6H6+uxbgKwsVV95u9ow8uw=,tag:eX45UFqac97GfPsALNAwUA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qM7II2qVmsIJquphnNo=,iv:Y6G0DDdj55R/qWWPHXTsizGzzIdap10ANfhhIbJXUU8=,tag:te5cAqEC20QzcFmZi81CAA==,type:str]
    namespace: ENC[AES256_GCM,data:S6yyPiUO/6WTEk8=,iv:pJaIMhdHJE0bOctJb+T0v8aKDVJpKvsKlp4uOahwfE0=,tag:nlJODOpxvTHTH9aAaMZ7Cg==,type:str]
type: ENC[AES256_GCM,data:rghy9Nqg,iv:qC8c65q27c1WMm12XoiuO7dGq8G/NPK2TnDOrJrY6SM=,tag:18HI5oJPHth4IHdgfHyf4w==,type:str]
stringData:
    HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:XmiSov399Wo=,iv:1Ogf4APs6vsul/sIGyQIdgnrFhM0wNyP2e6rPa7ICK4=,tag:FcoowkVdxTUaivFwx1Fiog==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2a2FLTlJaQWt6dmFGV1M3
            T0IwYi91NURWZE96aERZMEk1ZVJQaW54YlE4CmUwTTRyZXZocXpKMXRXbXZnU3BT
            eHUvc3g1cFlmbVZEQ280NTN3TnBiRmMKLS0tIHlPMnNZSXpkUUZDTHFMYnlMcm0y
            SXExdzA0c2U1RzVkdEhsYUxQeTlzSm8K5pzNXHN8DtRdWNSpYPwOJ9cSRwnhBk2k
            VjNANSXi10JzeamfBgDBQTtIJjDWOcgEX77lFUXIw+5ZaDKgRKRqQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T19:15:23Z"
    mac: ENC[AES256_GCM,data:2MYbv2OuhvVO1QfZeCNnZEV80uhSo5SivqBe5/zFnVFtvzkNZA4rE3L/SnMzPms2gWQDVFB7i0gE47lu8Pcc9o1A3FLED84ii0l7D4j+IcIyceDxQIwCLcinyAnI6ZBLo8CDqTbPgE0mB8TCf7/njynPocj4xqw/DEd+LTQY8fE=,iv:83lJP3WhCI+CGj+p5jbbvM1zNjtOTe90OAz76tJTxQQ=,tag:pogpokCWN2HrQ50hcDlZtA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
