---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  labels:
    app.kubernetes.io/managed-by: flux
    kustomization.stuttgart-things.com/type: app
  name: minio-httproute
  namespace: flux-system
spec:
  dependsOn:
  - name: minio
  force: false
  interval: '1h'
  path: './apps/minio/components/httproute'
  postBuild:
    substitute:
      MINIO_NAMESPACE: minio
      INGRESS_HOSTNAME_CONSOLE: artifacts-console
      INGRESS_HOSTNAME_API: artifacts
      INGRESS_DOMAIN: platform.sthings.lab
      GATEWAY_NAME: platform-sthings-gateway
      GATEWAY_NAMESPACE: default
  prune: true
  retryInterval: '1m'
  sourceRef:
    kind: GitRepository
    name: flux-apps
  suspend: false
  timeout: '5m'
  wait: true
