apiVersion: ENC[AES256_GCM,data:Pp4=,iv:cZMDD5su3Qdt/fZjcdsrPET1O9zvAdAI21PpL5Ru2Oo=,tag:tU7ZIdsc6feYNri2rdoAEQ==,type:str]
kind: ENC[AES256_GCM,data:8K2rmRBm,iv:E7KXyiIgaP5c66I9y/jfRbhVR84L0GKjEQJrI9HdGa8=,tag:z6tVcpctLYZOIdX+Y+k//A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LEsxwxWHfVMCpb/quB1H,iv:5mutNESsAlG1BYJmKZoeqWubcLEtxqqFtEASCT5Mjrk=,tag:PsNjzdXBQhssa9nt6/Yb+A==,type:str]
    namespace: ENC[AES256_GCM,data:J6MaMVpifbVDSPg=,iv:MBvGGau4BiRI4s05cA0v8IdtKDhTiJpqbmYVd96faHQ=,tag:KWRdjMz+t4oTghwGDQukxw==,type:str]
type: ENC[AES256_GCM,data:28W/z19R,iv:GWIayR35uI8YrGEl8Em+DozmgVUBmsrL45A3bQk6l1k=,tag:ACAX4DJh6bfdz7XXrENejQ==,type:str]
stringData:
    BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:IR8hQjGGV0S/OlqSu47hnPs=,iv:cuQ+f9OPxUAjkLZDE9o9xBS0vAaOEpR3Eh8ot0ofOdo=,tag:vPmHNQpHO6dF5JwCnz0vUA==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RmtFTHQ3UmdzRUVPOW93
            UnFuTFZnODNQTWhqU0Ziczk1ZG9tUng2bkI4Cnp6RGlkZ3F5K0lTTkFXTk9XU0ZF
            SGtiMkVlUkRwRWVWbEtQWGpmMUQ4QTAKLS0tIG1SakhTamxzWFNDQ0d1Y2dNWnBX
            UWNsZWliR1ZlSXNnUnVBQnhPWHV4dmMKLq0iI9QX4F6+6zzI/OL4X/ktjKGjTGMS
            Ie9sUZPJuogsb2OvCiLMiicsmc0FxyFBw1GfayKY+SEuOHjDOoph7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T19:56:52Z"
    mac: ENC[AES256_GCM,data:MVqFdaOu69w2mFxtqxkmcNPhTDOyRZqbXegnowzXMxRyuS+Efkbec12APE+S57aTv4bgOpXDShmgtojAHFQgbrVzLBqyXFiAEbw7GhdOA+CWuyRkdb9McmYVeIHZrSWCM0wQOFvj6vIE8fU+D9O9KML6wQ+mfZJjdEgiE/5i33w=,iv:Yd/ZRlNc0kGF2wbUNLkcIm7ED4dlseRun+TE4H4hM7k=,tag:9uNR6Cm0uGZvLUKXh62uzw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
