---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  labels:
    app.kubernetes.io/managed-by: flux
    kustomization.stuttgart-things.com/type: app
  name: rancher
  namespace: flux-system
spec:
  force: false
  interval: '1h'
  path: './apps/rancher'
  postBuild:
    substitute:
      CLUSTER_ISSUER: vault-pki
      GATEWAY_NAME: platform-sthings-gateway
      GATEWAY_NAMESPACE: default
      INGRESS_DOMAIN: platform.sthings.lab
      INGRESS_HOSTNAME: rancher
      RANCHER_NAMESPACE: cattle-system
      RANCHER_REPLICAS: '1'
      RANCHER_VERSION: 2.14.2
    substituteFrom:
    - kind: Secret
      name: rancher-secrets
      optional: false
  prune: true
  retryInterval: '1m'
  sourceRef:
    kind: GitRepository
    name: flux-apps
  suspend: false
  timeout: '10m'
  wait: false
