---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: u26-dev-packer-image
  description: u26-dev Packer Image for Harvester
  annotations:
    github.com/project-slug: stuttgart-things/harvester
  tags:
    - harvester
    - packer
    - ubuntu26
    - users-customized
    - packages-customized
spec:
  type: packer-image
  lifecycle: production
  owner: platform-team
  dependsOn: []
  profile:
    addedUsers: []
    addedPackages: []
