apiVersion: ENC[AES256_GCM,data:HwE=,iv:8/DEcinBlCOdf/2iYV2nyKHsWIdz8eBezvWOgjvr3ts=,tag:MCcn6/sxk/WXVTBG3PjxbA==,type:str]
kind: ENC[AES256_GCM,data:II/24X32,iv:NX9evqRNIuenD6q5NAP8KxRbN0gHuMmAVWLibn7s4eg=,tag:ZzlJwoKgA2Og16YPuIHcxA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:EZEOcUXZmgNjNaveKxo=,iv:D6bifET2PkrSroZJuFE/eC8nLIz7/Ktxpr1h6zc/Rf8=,tag:Wa2kdHic5ci5mgzjROgTuA==,type:str]
    namespace: ENC[AES256_GCM,data:i0Q1gIxa39sKouc=,iv:DbVNqvx7I70c1iw39qN+kKLBHav53Dco2MBJ7LQdJLI=,tag:E/Nz/01TGmPW1ijkmI1h+A==,type:str]
type: ENC[AES256_GCM,data:LA+s+FzH,iv:0Wa8nu2aTGxyHbWhwVV5pEriZIpGtC53CJSE1QBCWPU=,tag:fWKPdB/Xf04QX5uvpb/Aug==,type:str]
stringData:
    username: ENC[AES256_GCM,data:lqX/gHgVuXS8npJzEFzZQ/J3Tg==,iv:kpDqO2aGpx38GgLbQGzBkktPOL+FYSeZXlzAEGWQ36I=,tag:cUvI2326jZPb4vJ+OqP+UQ==,type:str]
    password: ENC[AES256_GCM,data:rKkM3271HTmHPZRlplYk5tXKqXpKs0Wby/7wzII5NZcNyWSqyg64Qw==,iv:wKEiJVIxR5/hteha4iBkiJHGrKrdMZ69+zrXkIp1jxM=,tag:/XeLwRSZVFNnnxQJTR2nOA==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWmdRdEJLb3pJUVBEckQv
            RWs0dEtRZUdIZ3ZSMFRpMjBiaHd6bmw3NnhBCkNJRkkxSDZUTUdQZ3ZCUDFQLzBG
            Qm16WEpYdE41dmQ2T1RPRVdGNWZqU1EKLS0tIHBtVWFsaGFHWU5ZMHBWekZlM0k1
            RHVmU1VjTUlTaloybkdVZVdiVkp5bXMKsCXUu5sfJF5FlgRRxeZ3f8crc90aV8Sf
            WFX2HG3S1VS7xNA4ddJONNefAqcenZZ7c6V8ikrHTR5JuKx2a7Rw7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T17:40:42Z"
    mac: ENC[AES256_GCM,data:Vj8qVYuQ5kRBf5cKleSkGPa0IFKfrn6OOGiXuBc44gmOXY+nSL7ZohYKNiS7Rg8EYKm0dr4cthsgyTVY9KQ5lJBCHl1WrdB7xYCgPEe+olPfNU6Q+P6F/Z++Y5p2XZsNYpXketSkljlzZDiUaa0Eo34hd/TollsHIq+iY9GDskE=,iv:RxHGqzJZ09o2FIJgwL76gAl4c4FcXbVuWOWJHoWY9y4=,tag:ZcYch4S6h6FhIyYfEa/vyg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:SyY=,iv:5MQQ7Z47QUI1fzcyNduasAYeBA49Y/GPv+HgxOnQA5Q=,tag:z3/GLfstX5Ak2g5QRLmjHA==,type:str]
kind: ENC[AES256_GCM,data:TZU2yV2b,iv:QXt0dLfeNaZwiVhbXnsmredhkyJBwUJGaIXUz0BPuKM=,tag:SJ2Ql/2Y3loiodLxBH/vcg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nP1GBiJ3BBY=,iv:wWs1OqXnfnpSzYV/5e0Mjd4MR4SOpp0idpzLVJvVpb0=,tag:xhhNpDB2AlKtNBUeBHaUVQ==,type:str]
    namespace: ENC[AES256_GCM,data:QjcjpLRI4FHDUf0=,iv:4WEasD6PxmMD5JfZbw+3eZKLBv5VZTqCcFBWEF+llN0=,tag:fU+x9aR4l6V6y47VgicqJA==,type:str]
type: ENC[AES256_GCM,data:RwCJRw0p,iv:fyNN8tbIjVn/+lnaEr1OtAOwj1FtA8qGzOmy/iHbGTw=,tag:N0rXSSaZY4NR4e/IXzub6Q==,type:str]
stringData:
    age.agekey: ENC[AES256_GCM,data:+bXY/1RU8aUPvBZCBBCsmClhxBsn9/0CUz55CUMDza//MisejAiwuk1KergtNDjXgfe3nCXkbD4L7MAVTsEd598QzYlh2doxZBY=,iv:+kkIQ2qf1YvET6b8R+0EzSfMGgNjiHf3IOeNnI7VGUw=,tag:s+T+4DUjW3lR5m11CxSNWg==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWmdRdEJLb3pJUVBEckQv
            RWs0dEtRZUdIZ3ZSMFRpMjBiaHd6bmw3NnhBCkNJRkkxSDZUTUdQZ3ZCUDFQLzBG
            Qm16WEpYdE41dmQ2T1RPRVdGNWZqU1EKLS0tIHBtVWFsaGFHWU5ZMHBWekZlM0k1
            RHVmU1VjTUlTaloybkdVZVdiVkp5bXMKsCXUu5sfJF5FlgRRxeZ3f8crc90aV8Sf
            WFX2HG3S1VS7xNA4ddJONNefAqcenZZ7c6V8ikrHTR5JuKx2a7Rw7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T17:40:42Z"
    mac: ENC[AES256_GCM,data:Vj8qVYuQ5kRBf5cKleSkGPa0IFKfrn6OOGiXuBc44gmOXY+nSL7ZohYKNiS7Rg8EYKm0dr4cthsgyTVY9KQ5lJBCHl1WrdB7xYCgPEe+olPfNU6Q+P6F/Z++Y5p2XZsNYpXketSkljlzZDiUaa0Eo34hd/TollsHIq+iY9GDskE=,iv:RxHGqzJZ09o2FIJgwL76gAl4c4FcXbVuWOWJHoWY9y4=,tag:ZcYch4S6h6FhIyYfEa/vyg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
