apiVersion: ENC[AES256_GCM,data:Gek=,iv:y7dkbTu7lzr7M36haiLH9o3D2yOvo0zWopOLc+JKtxQ=,tag:XLRukjI9mqYIozhDEwvNdw==,type:str]
kind: ENC[AES256_GCM,data:JGSTYePF,iv:1HyAJYlI7+LhZniU1gfVrvBxYCeQc/Banwdw7Otq7nE=,tag:LiRmXWFFugaH5M9W+vs8PA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AhOxUBfkFxEsrzVowbU=,iv:6LlVlbLKRtvGE/4IDsTtZDyNS6YMI2dBt+T/04U/cpA=,tag:OIT2COITPAqpE0+pIxb6tQ==,type:str]
    namespace: ENC[AES256_GCM,data:h9ncEgZPNX/ww40=,iv:+irlHF5hoiDcw7wzdjcg/jcbY9cHzxJEXkd+uNlTfJw=,tag:TcIVcI7AbcR9z/9ysx0cnw==,type:str]
type: ENC[AES256_GCM,data:JB9kbsMK,iv:b1lDij9DOZtpQmjoh9O4rDyqP15by58vsyAHLMcuz0c=,tag:lo8np8d74NBzjNyIkMrs8Q==,type:str]
stringData:
    username: ENC[AES256_GCM,data:BeFhRL2fJXxssrFqzaBE0Vkadw==,iv:jvGR+JwcWPtjU5ixiZGznw0PRA6FtDOSaOVbaMAS/k4=,tag:fOzHQoGSmk8YMVbtmrE/BQ==,type:str]
    password: ENC[AES256_GCM,data:5Sr1Ci868SFBFFYVmz1yHFWzxrkaOZMpeame5GK1QRhrcF0HCND+bg==,iv:ZxnTUPH5VBaJ6f1e1J3IxYKVDVwMJDT/mARrXjS90HM=,tag:p/0dhuTI5RpFa77c/TRAwg==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MFNWbGtqNkQwcG02U3Av
            VWJ1TXQzTHJJR0ZMQUdmSThyaUQ4T0FmSWg0ClpSRkl5RXd0VUp5Zk9sU08yZU9R
            bDhQbTVHRktCOStYYkxCZVcrQzUvZ2sKLS0tIERjZ21Ndzh5ZFZnNnI1bWlicWI1
            USt3UmtkSkV6QWtzeDhNbHNHKytVUjQKbY+9vuy7xKr6pu9/WHLmFOubf3DDDpLx
            4KBZ63MULDksl25v9QALMubFx1gi7OAinA0s9Ysz4+JMpv/bxeE63g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T11:52:23Z"
    mac: ENC[AES256_GCM,data:9ZThbiu01O8ueXeh9tfqci6v+czMB8cqQjI5gYncaw4gUF0o3rWXJMusv2WGDj+rcrfZB4CRD5gMUu8YNnWQceKDuf1OrkGI+z3eXd23ClJR7P/IxSv3NX+CiZNpKtlUGLXxehXvJxhEnayCNFW9nYXlgL3vaWcxZW+O1RKUtJQ=,iv:yIZDDkW90yHnhgVWWO38i0X947u0iYQMEJdjFPiBAw0=,tag:Qmbc1pQEmKHW9HnFetedMg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:sfs=,iv:rd9tcJv0u45Ld59aFaW+Us9fh0s124kYivksBgm72kY=,tag:Fq9BpsmOEXtc6N7qZNv6OA==,type:str]
kind: ENC[AES256_GCM,data:DG+HsXrl,iv:PWWTZUDVQv9dmJs/+mJwkUJ8rNcjISqA/yKvttPpbTM=,tag:uPyuv5E3QJC4r8ufCzYrew==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Zhi2pBQtWgQ=,iv:rxhtNH24OsS36tIL5yqdE/9EKQZlmdpUSkEWRW9Rxpg=,tag:WezAwJRqth5Jy48xZv29ag==,type:str]
    namespace: ENC[AES256_GCM,data:yD66zZmXRaTPWRY=,iv:a2YKqi44jvyAYq/VCFrubm4p39bh4hr0iLRpdr1h0oM=,tag:sD2hCuLu75ZE1B/yD7xeqA==,type:str]
type: ENC[AES256_GCM,data:7G3ensQp,iv:M8/Hu5RLWj6DIChOIGJMl6eBv3L5LhB+qxFsTTYCBQY=,tag:I3tv6CcaudZjKB24Zhwngg==,type:str]
stringData:
    age.agekey: ENC[AES256_GCM,data:hIEsX6umFEX7FRkJnpVl+Qpo+bH585ODBmEej8exeQ3dzpXXjhpm0nByxPjo2JVPzAGh9F3iw3AcTP8iDrXhI9CGkURpk6MOLYA=,iv:OD45LvMgh4HaGmu8jTbLw9vS9G3BBLFH8mdJFNSqFrM=,tag:TeKI4AW+8jn8a6taXCmWXQ==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MFNWbGtqNkQwcG02U3Av
            VWJ1TXQzTHJJR0ZMQUdmSThyaUQ4T0FmSWg0ClpSRkl5RXd0VUp5Zk9sU08yZU9R
            bDhQbTVHRktCOStYYkxCZVcrQzUvZ2sKLS0tIERjZ21Ndzh5ZFZnNnI1bWlicWI1
            USt3UmtkSkV6QWtzeDhNbHNHKytVUjQKbY+9vuy7xKr6pu9/WHLmFOubf3DDDpLx
            4KBZ63MULDksl25v9QALMubFx1gi7OAinA0s9Ysz4+JMpv/bxeE63g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T11:52:23Z"
    mac: ENC[AES256_GCM,data:9ZThbiu01O8ueXeh9tfqci6v+czMB8cqQjI5gYncaw4gUF0o3rWXJMusv2WGDj+rcrfZB4CRD5gMUu8YNnWQceKDuf1OrkGI+z3eXd23ClJR7P/IxSv3NX+CiZNpKtlUGLXxehXvJxhEnayCNFW9nYXlgL3vaWcxZW+O1RKUtJQ=,iv:yIZDDkW90yHnhgVWWO38i0X947u0iYQMEJdjFPiBAw0=,tag:Qmbc1pQEmKHW9HnFetedMg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
