apiVersion: ENC[AES256_GCM,data:oYg=,iv:u9L8dCxQ8hj6KMLWfsEDS8Li50cdRzZjcqTX4sv0iu8=,tag:wuY1U3ERH6CmfB4D7hxn2A==,type:str]
kind: ENC[AES256_GCM,data:8RieFHXQ,iv:e+14WjLyZXHZMQRd8uqFGhXQ4qEkczepsKrUAV82+ss=,tag:FC8Fu/4T1Smu40LSN642Sw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5COx3VHfa9zCKSno7a0=,iv:owIVfohvHlq+147MfP1P4748rpyekHPI5+Z1fyXBZVI=,tag:aZ79mwAlOHcmAk3Nly4uBQ==,type:str]
    namespace: ENC[AES256_GCM,data:EJ0LlEfzlAOLNWU=,iv:+pxXSItfED32WvDDqED1bqrmXo1PMWqEgN+ijMI54TI=,tag:66/rhgU1BUvyAxRbI6LnbA==,type:str]
type: ENC[AES256_GCM,data:Vkff1lM6,iv:imU5iwh/QGjNLjsK3CZGVC5sw9+yl2RkATHChR4uBps=,tag:zNCHt4/uprHdC3etaqvLrA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:Ych3M6RaxAFuIXlASrM+2C2ATg==,iv:xXpN9oO163892x4epmsJLrTNZXk5CVaAoBzdqXs0E8U=,tag:7PqY8t1bbuEADpsqM0Rbsw==,type:str]
    password: ENC[AES256_GCM,data:Pua5D7q/R5s6pbbhNL0c6GK7BjvedD7p8c8bVgVf5zBdEmqNgHcDxA==,iv:Lynk1jMBxXbo0v5SXhEJrrBFWgdoNTh+4G3DYXLjkAY=,tag:wA90otnGUd4ObSdqTvWy4w==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkK0RoYnlsZHhoZnJNczVx
            dWNQZGhHcEJHV0RHOHVoZytvQjdObUxVSDM4Ck9pN1dlbzNkTDhNdzJGeWRFUVlI
            eUhxcVhFY1NRK2RFcXBHVlFWS3JoT3cKLS0tIEF3MDZGVGxlVVVYam5VTUtWSkNV
            dUlmdjhvVzRPMnJWWWIwdzJtK01JU1UK9A6No7Zp40KfLfEm2ekmm8l62+a5Vdih
            DFUKTde1G5y18Zss+QoeTvbXChD0x1pyWCiCX+32i9+R113mymWqFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T05:56:37Z"
    mac: ENC[AES256_GCM,data:mYM+QPGU77Ssu9beAFie4COGzMhlySM/6c+C+Nn+4+HXxAHd3fb1d15qnPIf9J82IOHNKiGwStRHRqI0K8B66Krh3LbvNB2Erc7hiiS4+phoonFImgRUvjQzSR9+3c4pQT27FukSk5U8Lg7flzhIO6HDZYAu5UsvDD1n4t1FsT4=,iv:C72wi4CsmqCwZFJoXDj6LhYDB3wAnmN8KyNvaMULsXo=,tag:rOMOXAsaNVp2inEj+G/MBA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
---
apiVersion: ENC[AES256_GCM,data:69Y=,iv:rabDQAYnvcmBMMBLEdLfLZMeCAiBXeWSSAYzYroja3g=,tag:B8wXbiCcb1cgpa8+X64ohw==,type:str]
kind: ENC[AES256_GCM,data:10lpQDUC,iv:Ys/+uSZSfLMHRGyQQVs5ZQ0O9wbVPPMQTu5ctiiZZ+U=,tag:cs1Te9iEbvCNcw+/azdNmw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RAsFfwC5qRg=,iv:s4uZB1KpfInmScfBWi5yvGz+Ee92pinSKP431ZcT+6w=,tag:I52C+gQe1X36V+y8By4cow==,type:str]
    namespace: ENC[AES256_GCM,data:+k6irNqBEbsbORI=,iv:+if3Bac9F7M9fxS5AB4p6lo5tJxAOUujMUW6M0ToekE=,tag:wwye4HeYXakZI2ho4XOHmw==,type:str]
type: ENC[AES256_GCM,data:0AUYd3N1,iv:lAUPv0Je4w9u3nXnSS7CJBeyVqOZh3L7USgxCxQHHdI=,tag:5aIbnYUzQ1gvcY7DzpvUkw==,type:str]
stringData:
    age.agekey: ENC[AES256_GCM,data:nFTiGof9+7YYsNWrykuEKOq2QR/KYy8i/DH0aKJvl7kYVoppRX/9FJDCjqMmBPOVpX6mlKUANcKabqNqggfyyiCCfyOLd+QTrPI=,iv:pNQaysKVfBBeGXFJUZmAGEgcwKUOz39mL7eHiRtAG7c=,tag:h/K5LcdLWOYQ0DWi4sUx5A==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkK0RoYnlsZHhoZnJNczVx
            dWNQZGhHcEJHV0RHOHVoZytvQjdObUxVSDM4Ck9pN1dlbzNkTDhNdzJGeWRFUVlI
            eUhxcVhFY1NRK2RFcXBHVlFWS3JoT3cKLS0tIEF3MDZGVGxlVVVYam5VTUtWSkNV
            dUlmdjhvVzRPMnJWWWIwdzJtK01JU1UK9A6No7Zp40KfLfEm2ekmm8l62+a5Vdih
            DFUKTde1G5y18Zss+QoeTvbXChD0x1pyWCiCX+32i9+R113mymWqFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T05:56:37Z"
    mac: ENC[AES256_GCM,data:mYM+QPGU77Ssu9beAFie4COGzMhlySM/6c+C+Nn+4+HXxAHd3fb1d15qnPIf9J82IOHNKiGwStRHRqI0K8B66Krh3LbvNB2Erc7hiiS4+phoonFImgRUvjQzSR9+3c4pQT27FukSk5U8Lg7flzhIO6HDZYAu5UsvDD1n4t1FsT4=,iv:C72wi4CsmqCwZFJoXDj6LhYDB3wAnmN8KyNvaMULsXo=,tag:rOMOXAsaNVp2inEj+G/MBA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
