---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: sthings-rocky9-packer-image
  description: sthings-rocky9 golden (curated, review-gated) Packer base image for Harvester
  annotations:
    github.com/project-slug: stuttgart-things/harvester
  tags:
    - harvester
    - packer
    - golden
    - rocky
spec:
  type: packer-image-golden
  lifecycle: production
  owner: platform-team
  dependsOn: []
  profile:
    baseImage: rocky9
    addedUsers:
      - sthings
    addedPackages: []
