apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: harvester-repo
  description: Root catalog for the harvester repository
spec:
  targets:
    - ../catalog-info.yaml
    - ../packer/golden/sthings-u26/catalog-info.yaml
    - ../packer/dev/u26-dev/catalog-info.yaml
    - ../packer/rocky/catalog-info.yaml
    - ../packer/opensuse-leap/catalog-info.yaml
    - ../claims/apps/dev-vm/catalog-info.yaml
    - ../claims/infra/demo1/catalog-info.yaml
    - ../claims/infra/movies/catalog-info.yaml
    - ../claims/infra/test123/catalog-info.yaml
