#!/usr/bin/env bash
# catalog-index.sh — keep the Backstage catalog index + packer provenance in sync.
#
# Since this repo does NOT use Backstage GitHub discovery, the catalog is driven
# by an explicit `kind: Location` index (.backstage/catalog-locations.yaml).
# Location targets do not support globs, so the index must list every
# catalog-info.yaml by hand — this script regenerates it deterministically so
# nobody has to.
#
# Commands:
#   index   regenerate .backstage/catalog-locations.yaml from every
#           catalog-info.yaml in the repo (packer, claims, root, …). Self-heals
#           on adds AND deletes — mirrors what discovery would do, but explicit.
#   stamp   write git-derived provenance annotations into packer/** image
#           entities (who/when), without clobbering scaffold-time fields.
#   all     stamp, then index (default).
#
# Idempotent: re-running with no underlying change produces no diff, so the CI
# commit loop terminates on its own.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

INDEX_FILE=".backstage/catalog-locations.yaml"
LOCATION_NAME="harvester-repo"
LOCATION_DESC="Root catalog for the harvester repository"

# Scope of provenance stamping. Index always covers the whole repo; provenance
# is only meaningful for the self-service packer images (claims are managed by
# Crossplane / claim-machinery and carry their own source-location).
STAMP_GLOB="packer"

# Annotation namespace (backstage.io/ is reserved, so use our own).
NS="sthings.lab"

# Commits made by this script are tagged so CI can skip them and so provenance
# computations can ignore them (otherwise last-modified would chase its tail).
BOT_TAG="[catalog-bot]"

# Paths excluded from the index scan: .git, and vendored Terraform module
# downloads (.terraform/modules/**) which ship their own catalog-info.yaml but
# are not entities of THIS repo.
find_catalog_files() {
  local root="${1:-.}"
  find "$root" -type f -name 'catalog-info.yaml' \
    -not -path '*/.git/*' \
    -not -path '*/.terraform/*' 2>/dev/null \
    | sed 's|^\./||' | LC_ALL=C sort
}

log() { printf '  %s\n' "$*" >&2; }

# ---------------------------------------------------------------------------
# index: rebuild the Location entity from a repo-wide catalog-info.yaml scan.
# ---------------------------------------------------------------------------
gen_index() {
  log "scanning for catalog-info.yaml …"
  mapfile -t files < <(find_catalog_files ".")

  if [ "${#files[@]}" -eq 0 ]; then
    log "no catalog-info.yaml found — refusing to write an empty index"
    return 1
  fi

  {
    echo "apiVersion: backstage.io/v1alpha1"
    echo "kind: Location"
    echo "metadata:"
    echo "  name: ${LOCATION_NAME}"
    echo "  description: ${LOCATION_DESC}"
    echo "  # GENERATED by .backstage/catalog-index.sh — do not edit by hand."
    echo "spec:"
    echo "  targets:"
    for f in "${files[@]}"; do
      echo "    - ../${f}"
    done
  } > "${INDEX_FILE}.tmp"

  if [ -f "$INDEX_FILE" ] && diff -q "$INDEX_FILE" "${INDEX_FILE}.tmp" >/dev/null; then
    rm -f "${INDEX_FILE}.tmp"
    log "index unchanged (${#files[@]} targets)"
  else
    mv "${INDEX_FILE}.tmp" "$INDEX_FILE"
    log "index regenerated (${#files[@]} targets)"
  fi
}

# ---------------------------------------------------------------------------
# stamp: provenance annotations from authoritative git history.
#   created-at        first commit that added the file   (non-bot)
#   last-modified-by  author of latest content change     (non-bot)
#   last-modified-at  date   of latest content change     (non-bot)
# created-by / source-template are written by the scaffolder at scaffold time
# and are NEVER overwritten here (git author may be a bot/app, not the human).
# ---------------------------------------------------------------------------
stamp_provenance() {
  command -v python3 >/dev/null || { log "python3 required for stamp"; return 1; }

  mapfile -t files < <(find_catalog_files "$STAMP_GLOB")
  [ "${#files[@]}" -gt 0 ] || { log "no packer entities to stamp"; return 0; }

  # Escape the bot tag's [] for use as a basic-regex grep pattern.
  local grep_pat
  grep_pat=$(printf '%s' "$BOT_TAG" | sed 's/[][]/\\&/g')

  for f in "${files[@]}"; do
    # Latest non-bot commit touching the file (content change).
    local last created
    last=$(git log -1 --invert-grep --grep="$grep_pat" \
              --format='%an%x09%aI' -- "$f" 2>/dev/null || true)
    # First (oldest) non-bot commit that added/changed the file.
    created=$(git log --invert-grep --grep="$grep_pat" \
              --diff-filter=AM --format='%aI' -- "$f" 2>/dev/null | tail -1 || true)

    [ -n "$last" ] || { log "no git history for $f (shallow checkout?) — skipping"; continue; }
    local lmb="${last%%$'\t'*}" lma="${last#*$'\t'}"

    LMB="$lmb" LMA="$lma" CAT="$created" NS="$NS" python3 - "$f" <<'PY'
import os, sys
from ruamel.yaml import YAML
path = sys.argv[1]
ns = os.environ["NS"]
yaml = YAML()           # round-trip: preserves comments + key order
yaml.preserve_quotes = True
yaml.indent(mapping=2, sequence=4, offset=2)  # match existing block-list style
yaml.width = 4096                              # never re-wrap long scalars
with open(path) as fh:
    raw = fh.read()
# Preserve a leading `---` document-start marker if the source had one
# (ruamel drops it by default — would create noisy diffs across the file).
yaml.explicit_start = raw.lstrip().startswith("---")
doc = yaml.load(raw)
meta = doc.setdefault("metadata", {})
ann = meta.setdefault("annotations", {})

def setk(k, v):
    if v:
        ann[f"{ns}/{k}"] = v

# created-at only if not already pinned (first stamp wins / scaffold may set it)
if f"{ns}/created-at" not in ann and os.environ.get("CAT"):
    setk("created-at", os.environ["CAT"])
setk("last-modified-by", os.environ.get("LMB"))
setk("last-modified-at", os.environ.get("LMA"))

with open(path, "w") as fh:
    yaml.dump(doc, fh)
PY
  done
  log "provenance stamped on ${#files[@]} packer entit(y/ies)"
}

case "${1:-all}" in
  index) gen_index ;;
  stamp) stamp_provenance ;;
  all)   stamp_provenance; gen_index ;;
  *) echo "usage: $0 {index|stamp|all}" >&2; exit 2 ;;
esac
