---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rocky9-dev-packer-image
  description: rocky9-dev self-service dev/playground Packer image, layered on golden sthings-rocky9
  annotations:
    github.com/project-slug: stuttgart-things/harvester
  tags:
    - harvester
    - packer
    - dev
    - playground
    - rocky
spec:
  type: packer-image-dev
  lifecycle: experimental
  owner: platform-team
  dependsOn:
    - resource:default/sthings-rocky9-packer-image
  profile:
    baseImage: rocky9
    goldenBase: sthings-rocky9
