---
apiVersion: v1
kind: Namespace
metadata:
  name: backstage
  labels:
    toolkit.fluxcd.io/tenant: sthings-team
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-ca-env
  namespace: backstage
data:
  NODE_EXTRA_CA_CERTS: /etc/ssl/custom/trust-bundle.pem
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-catalog-config
  namespace: backstage
data:
  app-config.catalog.yaml: |
    catalog:
      locations:
        - type: url
          target: https://github.com/stuttgart-things/backstage-resources/blob/main/org/sthings-harvester/org.yaml
          rules:
            - allow: [User, Group]
        - type: url
          target: https://github.com/stuttgart-things/backstage-resources/blob/main/services/sthings-harvester/catalog-index.yaml
          rules:
            - allow: [Component, Location, System, API, Resource, Template]
