apiVersion: ENC[AES256_GCM,data:O7Y=,iv:vaCBDhjAKRk74OFynVEYPXn1K2r/3ZzRsyaTl2ul4aw=,tag:yoFqi/PqxlpiMlPjSc7vWA==,type:str]
kind: ENC[AES256_GCM,data:29l0C0Hq,iv:6JVaFnkUxoUJREmgPytyDwH7J9JOfjWlwEfYyIZH6yg=,tag:fNgo/iuIvGcTYiqnkDO1nQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FUtfAci6vOm3EiWrz9A=,iv:q1y5xszoRYTvWewaMn/EGwbBe8nDuGf6DrQN7tjQDf4=,tag:liSbQdVD9Oi1HufdUtRArg==,type:str]
    namespace: ENC[AES256_GCM,data:ql72tMoqY31OQL8=,iv:yXmN008f9nZ3QOXcElSZEvSGwNiAAlkwyvPeCABpcp4=,tag:jFQ8825/1vAPtc/L59Kjow==,type:str]
type: ENC[AES256_GCM,data:AwH83dKH,iv:F50ZoLDRi0MvEVLR7X0Uuu2he5KJeznZjEMtqXvgnwM=,tag:GUAzKqsSldt+YLnm2/WO4Q==,type:str]
stringData:
    username: ENC[AES256_GCM,data:HypyWyMHW2xrs8MCHQr/gJWl8w==,iv:ZGCcx6K1kAxghDBATwpy3h2nQaIWtYKitV7/QN5Xyr8=,tag:uYYXWp29xZj25aj+cUV8yg==,type:str]
    password: ENC[AES256_GCM,data:zKoPdM71VHDjCOeGK7TbrkZBTbyCAeEpTJNYTkpOdy2myAecL8nMeQ==,iv:kDzjSpN6IPuuiblIqoGchCxoT95Gleu7dhiYKvUSifo=,tag:l5YDR5pAXTfHzapSkExd1Q==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSC9SYXcrc1U5RVoyWnBK
            ajVnbGJRbC85MGFSMTREaWZzZGRmRDlnRlVRCmEwYlpqTzcxR2tLYjBLblJlMHk0
            eVVsNzU0akI4WXFQSGJDNGZsV3l1RlkKLS0tIG8ranNiOXBoSUZoZjRVYU1sRHI2
            elNNS0tzeHNRaHIyYkw5U2N1L1g2cjgKFfgFk1F9NJNj5iLou4JJcOwjy4aa8FcV
            zHuBFynbzGyv68z68aoqk59bsDeDmGsnwsVgfV64P2SCUEowUav/AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T15:18:26Z"
    mac: ENC[AES256_GCM,data:F1KdWnA2Y0LNw/bgnNz6ON7PEVZDt4RYcjssQhx2tDME7j0a+5swbOZGrk2h4pPFBkGVHGsAyEuGylI/ZluD+Hbg5dDhr9uEs5ynXEkC3TG9N+4NN8IIponKVltV3EDe9PZGMcCL9QUV7ZzipuJC46npgsAIyJ5Joz6spTfK7b4=,iv:jMTJIOxKkfW1By3Vb+XDiO3sjjvG1DLPJL1p/6kmbLs=,tag:w8S+Zd/0b4XQalKaN/Llig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:PSY=,iv:3/KHVpTMVfpPl5vzQw5qdnp78AOi7SlV1jn9Y368QKU=,tag:AZL+6UB2HgWPhiWV+KCY+Q==,type:str]
kind: ENC[AES256_GCM,data:1wfidFCs,iv:MPLacBqwXXbBbMcep5fw42Xw1f631ZBRFZKiAbjaq6U=,tag:7R+nDJ8yRtGfDJLapgqeMA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ELoMUT/QvDI=,iv:HClxLo9btfKHrtQ7QkII45x/Cji1RG306sFHnxfeZkk=,tag:Iq+Jy5x2sekn+Prf411CSA==,type:str]
    namespace: ENC[AES256_GCM,data:Vy7PbBMc3zm/3u4=,iv:wDI3WHHJ37Le74hrDDpSMsEG3TUXeTii7f/VpSsHUt8=,tag:p4IhMKAwDrI2Xqw2eVo1tg==,type:str]
type: ENC[AES256_GCM,data:toog3Yep,iv:vh3I8b1ACdSZwRb6u33nEXSfnGC4SzCRGqqIpS7ityA=,tag:0K2+RZNnRd7jegBZEFAKvA==,type:str]
stringData:
    age.agekey: ENC[AES256_GCM,data:Qe3iBHetoH0t2AuzWCf5vwfF/wvMS++CPy8vgANvIeZPP6rjjg8Riw3tcnC7BlAihGrw8n/WEwDmRJfVnqW35BrEY8S3dT1+svU=,iv:XJVnLl/NL7yfFQCsVlJv1h0I06cwKGXLSsc5xAYh5N4=,tag:D3Ea/mCCPljHuiWBhIDG5g==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSC9SYXcrc1U5RVoyWnBK
            ajVnbGJRbC85MGFSMTREaWZzZGRmRDlnRlVRCmEwYlpqTzcxR2tLYjBLblJlMHk0
            eVVsNzU0akI4WXFQSGJDNGZsV3l1RlkKLS0tIG8ranNiOXBoSUZoZjRVYU1sRHI2
            elNNS0tzeHNRaHIyYkw5U2N1L1g2cjgKFfgFk1F9NJNj5iLou4JJcOwjy4aa8FcV
            zHuBFynbzGyv68z68aoqk59bsDeDmGsnwsVgfV64P2SCUEowUav/AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T15:18:26Z"
    mac: ENC[AES256_GCM,data:F1KdWnA2Y0LNw/bgnNz6ON7PEVZDt4RYcjssQhx2tDME7j0a+5swbOZGrk2h4pPFBkGVHGsAyEuGylI/ZluD+Hbg5dDhr9uEs5ynXEkC3TG9N+4NN8IIponKVltV3EDe9PZGMcCL9QUV7ZzipuJC46npgsAIyJ5Joz6spTfK7b4=,iv:jMTJIOxKkfW1By3Vb+XDiO3sjjvG1DLPJL1p/6kmbLs=,tag:w8S+Zd/0b4XQalKaN/Llig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:ois=,iv:FITA+iaQ9Bgh8XRG4sJmfEVEQoEvkh5XDKN0YLvxhSI=,tag:QQoRIUYMgR4tsAkm5KuEVA==,type:str]
data:
    UNSEAL: ENC[AES256_GCM,data:niA/JX0qdEVl/2lmd2st2umZcj44ajXh4RFIxIVqa8bwes+fJaRnjmKk5C7bK+R2Awd1iDGz69ctlvMy,iv:6xTOsEduSX6170fav5TAtWLmjISPrF4peEjzX+P8wM4=,tag:HxAW9Zc7OTqgiyNX2yKzOg==,type:str]
kind: ENC[AES256_GCM,data:4gXrmGBm,iv:1vssbh/dKQWNrw2bDeUBoGO/nCfON+rpLctC4m4hQig=,tag:hm9u66rPm9GSOS5OQGkaew==,type:str]
metadata:
    name: ENC[AES256_GCM,data:54guwmk=,iv:aUCeTDd8DFvHona3Dj5ZylEGEB/FnpUu5XTwELl7pTk=,tag:w9LsMljr4uYw7yZpv/K0rA==,type:str]
    namespace: ENC[AES256_GCM,data:ELFLBxvBxV/fEQc=,iv:F1Nw6aJKxqygGeEflTaDkaCqwh2//B4Z8dPEbTb3sOA=,tag:1VsVuhsycf7GowGoVfPmfw==,type:str]
type: ENC[AES256_GCM,data:nFhEoZS0,iv:DzijLBpvPdsnt7L4LJkVuaymetcZWN6QnxFJjKdqzho=,tag:uqjHv3zxbGOlKfvHknnq+w==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONWgxenhyTmhxZ0NQOEsx
            OW1USC83bGVUb1hJTGsxVm9EL29OL2oxbWxNCkJtSXNndW5VM3pvZDdvNnBwMFIr
            S2lLaUxEcmtsMVM1ZmZibWtRdEk5TjQKLS0tIEpzRjZFb3hKd05ZQVZKdDdEaDJK
            UjZ2TERreGdNRHVHK2I0WEV5dFNXaXMKPG/rnuO1R37d1wXktVWQGisY13HmpoVp
            /q6gsFMbT6cCs0lXFKYsLvyEAhnDO8GPXA1TD3zKxWZUqFchzIBzKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-02T13:53:31Z"
    mac: ENC[AES256_GCM,data:FcIKFFKRdK/fvkV1BwqKIrbV7KBM5tmvTnoiC/yjh1bRBxSRJK+Ri5fpMTji2xFfkyTcrVTLjAZ45/DCgqePCb/wNvpFoZY2sTpGnfMgBfOVCwmib/t1ynzmkOMYYn6IgYUTiVtEed/aStCS1UJs/PDSfDwgfpITjud24tDVzGk=,iv:rw2X66+z4T0WFO9f1aBjeDRfuOCZBxa5dTfV/XHODFI=,tag:ewAqb5OmAY1Mn10Mr2KMjg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
