apiVersion: ENC[AES256_GCM,data:9hI=,iv:FSMGI3CMD8Z2k4Vr0BNggJiCmTVFahHp5wfVWwJcaJ4=,tag:WS5MRR+xkat2H5J+mT4QCw==,type:str]
kind: ENC[AES256_GCM,data:WJhYojdz,iv:SUlgtT9stDSHbHDsvpaORJakjdPtmSO4KcnZsevAvDs=,tag:6xqTyDJ52r7Tt6rliodd9w==,type:str]
type: ENC[AES256_GCM,data:QSoGnmmP,iv:vu2PaQCUSMJFiZSp6fZBQ68y1snq4gnCfbZiJ67tAAM=,tag:nIN+XZo/m41E2lWRg8QG5w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aqwG9FAry/Cp3Bdx6tcuoqwuRw==,iv:So/DUcoaU0rQsLgm5XcRMjEz3FUCnkD/OS6nBCse7GU=,tag:rPQ965pOJIU0uTiiRnz8ag==,type:str]
    namespace: ENC[AES256_GCM,data:kWJWPYNeITBG,iv:0Vx35fGCG0xzQjkeF/OdaR9hPGRLTN0WfPu1zOeZm5A=,tag:nrV4Mt7Zvk88QsgOpaFHcg==,type:str]
stringData:
    ANSIBLE_USER: ENC[AES256_GCM,data:fYJj7eHn1w==,iv:cpiRGW0dE61LRLd5jw3+gFBWCDgrgTqCZznpTIxnC9I=,tag:6j+jdlliQjGxOXmYggFhtg==,type:str]
    ANSIBLE_PASSWORD: ENC[AES256_GCM,data:uo4t4blJ79k=,iv:Uo6FLRzFJ2dsw5jyIof6NEy7Gsnrki1hoY79KJytF1E=,tag:IwFdzOw3OYopioQK4MVD7g==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVXlhQWdFT1R3VDRDVzY4
            eUR5d050dVVkYWdYelFvV2w0M3p6b216d0hRCk1YQjExQzZNYzV6SFZCYUl5d1FB
            RjNibkVuWFpkbXZlRmZKaTVKSUQzWk0KLS0tIGMzR1NaRHpXWnphSEMrbG9BYncv
            Uzh2cDZTOEM2Q0M5Wm1TMnVjM3F3Q3cKNRo8BvJRVBvc+OIhe9C0oDV+cwlhp21b
            FmfriYKdthEyEEZolruPZVzivws72Yv2R4xfJ1WUMTjkLYs6mjj9+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T13:07:15Z"
    mac: ENC[AES256_GCM,data:rXUtgvsFtokGdoqT53LTmC3UxLb31AFebEYu5vnBTVsWCNd9isOsOPrlPiYtbCUwrgyEu4XW5y3qOC23bjvB08A6jLPne7azbYQwwelB7zh/a4Sub7K8NSIAcGTcxebw2rdnvjS36h/TXm5IIsv/utary9RP4V3uymh5OLukrqA=,iv:8JcrFtnrLa4hW31bnvpiD3dB5Boj8WjGsT+cTltDvL8=,tag:VIMUooXZgPWiNsrje+0ndA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
