apiVersion: ENC[AES256_GCM,data:nMY=,iv:fojpmLP89XFudrPzELbpErgNgJDjGmXSUx+uk2Ttcd0=,tag:KLZjTMlYMvmVTqInWrypDA==,type:str]
kind: ENC[AES256_GCM,data:WgzbwwAO,iv:UieYBjNnCLbTuzxdUD3jbtqMot7+2th0NZwvXU0WJFo=,tag:wYvncAXciYOn4gaR1akPQw==,type:str]
type: ENC[AES256_GCM,data:kaqwQfmE,iv:htctpV8lvHF0GbBSxIqb4Qjt6nCxI6jjezuGg1I8OEM=,tag:r4nsubsBQEYvSDV24vJsBA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aM0n93Naj62ocjmsJ9DDVMUDLAJpIiIqBe9u,iv:6PnC4bMOKUzIG14Pr85LWalEKmU9v3wHQMhO6SWsqPQ=,tag:7VBEFJS+SRLrVn90MBps9Q==,type:str]
    namespace: ENC[AES256_GCM,data:FsP59rCsR5eqGMjeioTN4tg=,iv:zUtFYxxooBM9IeaWbVMxMygAGfs9+4LnUjpCVHvZKO0=,tag:LjTwTPRdtuFXBdEj5qAllw==,type:str]
stringData:
    values.yaml: ENC[AES256_GCM,data:cSPN+JWRXkd+DS7zD1H4rpFbFssyXbIEOZK7+XDS9ZAIg+RmL2vS+FfoN0NcsC9nS7Tehlb/zTvSMk7Tx5rJuyQK,iv:eV7t6kYWyicbiQpDzc1ZchzzlIuc/9Ax7oA+2XaTK/I=,tag:fhrBE3HErBA0zp1/mt9VBg==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVXY3Z2h4QzA1OEt0QkVm
            STRvRDE0THVDL3JKNjRpalBFdytqcGpwbVd3Ck5NczFxT2laQldqOFNTbjVYdWhC
            cXFiSFFGM1ptZlJFYjdMZFZ0SHdFTncKLS0tIFlpN0JoU0NJTlo1K2RsUWxvVHZD
            WmhiTVRTTyt2ZGRuVlJmd0I0SURRSjAKygAwykuyN7ZS1b5UZ3ghZUUuJQWxQ+Fe
            Do8G8/rI1gbGF5jYau0Eui63deHUzMM3+HQ6HuC+j3aF1/RiHuic2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T13:11:38Z"
    mac: ENC[AES256_GCM,data:ogFHzRVhCEKDbnr3OsJ3sEbkAQpy2cpzdfRzedfd7Lgbiaac88D4H9hTLWGA0UK18p4PofdisxXfDW3d6R29RbeMO2SboULj85YLVv9kLptmiVj5gI6WUsaxbXloIawgAy/Kh2aMQM4AODYDAd2T/iYlVIzTpz2m1AHDd90Aras=,iv:V3FwIaF9br4dA/njbxsHxPlhqTQJy9B6adhSTl6T6Ik=,tag:aCmLqiv05JCdC9rDnEc53w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
