apiVersion: ENC[AES256_GCM,data:uv8=,iv:07hHMFYZl4G7dVBskWj6tqr/avSfqy9NGUyYsTRaouc=,tag:lHz14QO8FvV+ZmffWi3PEQ==,type:str]
kind: ENC[AES256_GCM,data:wsQPA1Ci,iv:Eve5E1a1ogDPhEqc4nBHsd+CRTyqVM5TCPYwFZ4Yo48=,tag:eSVRN2idKltwYIzthxRM2Q==,type:str]
type: ENC[AES256_GCM,data:Mt2E9TI0,iv:a58Egu+nHnOX+hZauLqvYrdWBIeE7StbJyJ4fSC0QSw=,tag:oizmRs2mU0Mo1Omzj8fSuw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9LSJ3xbNz6IpWXcvMA==,iv:9eh9kxWujTY6+fT2bJc3FGZ4qxb9y2+hq9Y2Pu/lhmo=,tag:Fd1Gy9wezLTNZ8G3WuBwWg==,type:str]
    namespace: ENC[AES256_GCM,data:00dp6fGg5Th2sLG1yYGYkdg=,iv:WrSuHGDvlA52Ff1Wy2SNZFCpli+s9v8rkjEipgI6m3M=,tag:uS5zh2xpdDTNe8W2zPU33g==,type:str]
stringData:
    secret-id: ENC[AES256_GCM,data:PmfoPTDgceY4uesEhe4ic4JSRF4Y/gcDSAEU0suTWxoRA82Y,iv:REpLqW7aLe2Y2ttEtCsPr2YtzG5dzANqGHsI9kWS1Z4=,tag:fKZ1YAJH3QFOvGGWJm+VCg==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUEttUjhSNVRaUkVJaDJC
            K2pyalVUSCtyNitzOHJkU0FyOHpnVHFMdlY4CjdWN0JRZ00zY29PMnIzcUc0S0pL
            eG83eC9vUzJmRUorc0F1QmtjMTlPdFEKLS0tIEw2VklidEdsTWdVbEk1TW5sd0F6
            U0xKTVhDOXJMUXVQTG11QzBIbEtLWm8Kgt/klH49vROcyM7yUOiwAntKuiSP064b
            wh7TXrdpEBqy5B0XCcUurJuo+JBhOp45l6D8uO6iOCM89jvfYlpjmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T13:11:38Z"
    mac: ENC[AES256_GCM,data:WAP6Tgnn6xuojQZ57Oab0d072h4ByTPqTvSq57nsAFRe/D4UMfGFy20SY42Kcj5jVGaql2rYQeyzM67AaTQo0zkLEwTiWPwq6uYxbCb+/rztOqYfY1iog/U52+JUYNoGDkLXeE91n6WLtxtcyP4OFCml7cIixz2t9svq8TGpOkA=,iv:cEpNIc38V0hGQq9ZcaX3v1lqITUOqm8y0zT2wiZjTNY=,tag:R4kHxSAWaUi1gLqP/se9nQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
