apiVersion: ENC[AES256_GCM,data:WNY=,iv:2CbfK7vrMjBwsNQ7nKDebPOqXzdxo/G/ZUdhCGi5u88=,tag:HNN+hJpBBVgmhCQ0+hD6DQ==,type:str]
kind: ENC[AES256_GCM,data:4eRM6dhC,iv:OdrhWm2s2jd9eJkxg1jSr2xNhWveev474Kn5OnHS6d0=,tag:7z9F8VnDTSPnzgIIVJHsXw==,type:str]
type: ENC[AES256_GCM,data:E3c+OoA4,iv:TNPYgxMJMvy3a0F5UN1pF63FRquQbsJfhgy/CjFjzLs=,tag:BHgmlVmggNwL2a3iL9Cu1g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZxrahoeF02+m89vVa648cdx5Y4NrUlE=,iv:cl3Z77++AFtypqe1MmoalmbX/zfcbzYdLrnS8XBYoFk=,tag:bZ0s7LVMB/lGc2WlmX5hpw==,type:str]
    namespace: ENC[AES256_GCM,data:8L2fY0Ih1w==,iv:cWXmqTDr3ujyzgPcqD3BZsc/oibp7c6QRHk1X9HrmDs=,tag:WestD5vZeReZ4SnthfoBNQ==,type:str]
stringData:
    terraform.tfvars: ENC[AES256_GCM,data:Lt+DuDxM7cPy75rOlh1NJnEBuxeIonDo+pqnGg2aY5ytzYB8ENxnyW3dUEQOT1Sah4PhI6Gl19jFAWP5K3A/POuvCIi+odtmH8vG59epJME5zceBQfc7G9ucQWjgsH62NkrsfVULnHBfwx9orEk6,iv:zP3ISbpD6vPomHShc28nY7kYRbbaTtPv7IRI6Ddx/po=,tag:sQIMxfDlhA9FlXkvSnkXqw==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSU1RQNkZ1eTQvdy9ld1dP
            KzFlb2RKMkwrc0k3RXpsOU9vY0lNYStJRlVnCi9WWFVUSzBYa0pneDNucklDWEQ5
            QlBFRkpCZlhXZHIrczIwT3piaWIwNHMKLS0tIHVHT2hOcVlRYlYzaS84Znl4VEY4
            ekxHSzI0NTgrU0JtaGRmOGRieUVNRzgKIngi+WhMxGHZfeDdGsPplnPs72tEQMpy
            YJeGrUnYrdPaFkvXcVf5uyqGvtDkX8cemygYYxTxD8OoJpLKjL5d+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T13:07:16Z"
    mac: ENC[AES256_GCM,data:jNIN6PKTVed0/0DXz/ft+BVEOrmhb3F+gxc8YXXyKbjdbW5xQymq/UWJXJwNZ7cWpgVpIz6Os/wuwyQaKFYzTBeNrdaWov6oSvzuag8voZdC1nZ2VwwEEXDrtEFbz25ooer/8wws7Otd6TIWjyke9s61JeoXAIv4DhcSsG0zdRM=,iv:B65Gf4QCxxFN8tUnjJBZ/byPj8alT3iuPPRp6lpkg2c=,tag:IJRNg7qlEFFue/C3laH+gg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
