apiVersion: ENC[AES256_GCM,data:GBY=,iv:iw46fiutiPQSi74UtnwiJQgFBTeKwp+tj6VTD2F0sVI=,tag:Ipho4mDcSL/FN8Vw3O4pFA==,type:str]
kind: ENC[AES256_GCM,data:E64EQPYI,iv:7qsylmd3VDGJyJ7bByDMaW4nVpZ97fx3yGlSOh3CGSA=,tag:RF1qo0cZh7f88n+cBBt9Vg==,type:str]
type: ENC[AES256_GCM,data:6rWLH0ik,iv:7U0+dBuF1umFtUdLsLIPOyUJur40vO+lKfsNoOjlc5M=,tag:Mx7Ow+ySAL2Yo3F3sej5CA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QpBORAbx+bNHyyp/WZSL8OiSP4Jpn1Eaz7d6,iv:aSlVfZ3PzR8viD9lT+f5Z1rXQCG+84lSl0YLNxb8HAs=,tag:HuCIvR9Tf92QL8C5DdqgdA==,type:str]
    namespace: ENC[AES256_GCM,data:wlyuJJ6lgs9U7d2U0IDy/h0=,iv:km8nd5DBuI8BxEQ5DvJ0Mryp5Ls84j9xIc6386MlAuI=,tag:W7d0xggvMSxrFwBvEqpMPQ==,type:str]
stringData:
    credentials: ENC[AES256_GCM,data:ljItgJurX37DiZlaLQM5rFGbuoHeocPY4XUjhHh7esZkoTzwuhkMmdWCI15OsKsbb2eAbcOM/EzIMXH46sCo/rZcotWH1SMthftJNkaS4+5ue0i1H0W/ZYtFqDzgzMlGAbfI/5Vh7ar0PmUhVnTsl9wKeXj3rkShTnn7HK0v4eDMBDY7KXr+JcYXAG2MNQwBIft2JMFIuov859pgX8IPGR9T3SVlYw==,iv:OMtD3SCOh0rTK+tUooyEZQyAQaO0k/nhJEsIoT1BOhw=,tag:pDGlb/rQVLTsi6adLtMqjA==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkN1NHNnNLUUFvSVYrRkEz
            T0lPM1NxT3g2cmFPaDY0bys4ZVg1YlAwZkhJCjhEOUczVU45eHJjeVRTYy9zM1Bq
            R1pJMDJBMklIaXlRREdLUTdRV2MyM3MKLS0tIEpKSDRSaHdBTGl5Z3ZOWDA4Y084
            b1VmbHRYWjJndGJKL2lUVExXMkhMakUKSKsHp4kHTN/OGpxsqNk6nfkhHI61ZbcU
            1Qa/zud3Dr6WfUeQsFCzsKfWNC9XggPw8fzPCk2lhxZ8B4gvWtlxuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T13:07:16Z"
    mac: ENC[AES256_GCM,data:hYhpX+d2tRJV84YJLniU97IEctpyUMDquv6H6+aA0esWYP7PL5c9iabz4YQ+F0E6ijLnIikMZwEQbDhj/MpSmp4jGw3giOZZJ3Mqb+2SUMR3F0nO1v44KDgl00zUbTZLs6amECDeGxx5uAbUGDjo1cCIKokjzGMWdn4JvCBGS+0=,iv:hUykG+Ej69woWT9V+jQ5u8DUyX4bcvR7VSPssqtUa88=,tag:0xdRhFei/VccdZEGw3bpZQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
