apiVersion: ENC[AES256_GCM,data:f/Y=,iv:9AZ5CCljuE8QSxOuvp1g0svM6G1KHeX2d08LHTLfyoU=,tag:wMrjPxpR286aFWOykUkQaw==,type:str]
kind: ENC[AES256_GCM,data:47iMvTgy,iv:hc/ejdplijtS1sd7oxoPEoJp16UX6khMPfTwtvnqOr8=,tag:jr54rTbYeoi3x3cVh6gGkw==,type:str]
type: ENC[AES256_GCM,data:lQu73n+H,iv:PKnHkAn5JbyTq52zkkxmRRfnaEyQPUuq6HT9BNAsLiA=,tag:vEKp8jlNXyOdzEMmoS7iSg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ovsGL1RbikMC9OO7bfw2geXN2a788wzcMjyhmDo=,iv:62csQXuw6UAhLnz6U2WjLse7Ny4zEYVfUgJo1rIsVkM=,tag:ZHFmazots9I9NAkHOippsg==,type:str]
    namespace: ENC[AES256_GCM,data:s8I8p8tWC2fCTIJZwi5i+V8=,iv:l8lOA7SafaIRIqHyuRdJIGXEiU7n723S+gLgz552XIE=,tag:STP8xE5c4pedHwaWlyBasg==,type:str]
stringData:
    credentials: ENC[AES256_GCM,data:qpRKUBrUAArAbT6waJa+PUbWaUdgqqJBHRqY1G+G/ffJJnDlrpv3K8yHmHUcgGaG6Rusn0AaF+0MhbHvarbCevlV7oy9IKkOxM5m2tfNQ5w8XBPvKMCMsJs/B/skm0LEHj5SlHjEA5lUvBmYT2L5FHYjTNWX3+qlSKN6BVuW2bgJGL3Eg14fjYiV+jjZPb34/Oi4qIYUoH+5BD5nV8iXku4hPRUvcA==,iv:lfOM1dENkub+8zIERQIELhXuPL3nIjQcysa8ipwWl6U=,tag:zUsFwZGQSJCbhaEeAVlWCA==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBab0s0RVBEOWNEZElnU0FM
            QUxXajU5dDNkNEV5MG1XeFNpUklYVzAxNVNJCmU4MDNvSFNPb0xZWlk4RjZSRXAz
            SWlEM3ZKRWl1Mjh3dUI5a1hlSDhqZEkKLS0tIDdtd3J6ZXNJS0VmSDhoSTF0Q3hx
            a0RFOFZFbkp5czNPcG1ZMFpkcHhQRkUK52y3egJeP9UTqoqTGxHKuI4a6kfKNfjA
            odKAzo2Fda/fettjPNVGJJEi7j2KnZ1t+mSsJVG2mMFJKGjkIHjGNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T13:07:16Z"
    mac: ENC[AES256_GCM,data:WDJd0EeNKlCmLRNlMT4tzn80ln+H+PG32b2TJk8v2O6Nd9idoFsvZq8YT8sQNrL4qDVc9aPDiPTEBMS6nwSOYJOpn6CPGBoiZBw66AcUDHN6lu9alAXVfc+giT5tGUwKeBUhduQ4nhphqZUjVFTqRZbjTigps93LNUAZEGJHSJQ=,iv:GZm7m3FpGeYhI/24Z5w9KzerBX9QpdB1I4V7Z8nfpKQ=,tag:J54fj98OVRpOZCgshmJKiQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
