apiVersion: ENC[AES256_GCM,data:F8w=,iv:birtsmcbbxLQm3J3B0u5zEPrFPe8NL4TuentsskkUFI=,tag:XbT/iuzfSmLi4qDZ3Auk9w==,type:str]
kind: ENC[AES256_GCM,data:NLzcjyBv,iv:rPaCIyoLGHaGf2lR1tSUgvC/5YyMAYcxHl+Fbe5c1b0=,tag:0zJCz3Gv9K5MVNoeH0tF+g==,type:str]
type: ENC[AES256_GCM,data:/2fLs43E,iv:T6mZouyFEBC+ulHY6X8+Vx3O1S/f4zIPJPS+YdRpvjI=,tag:tl3wx0uxOs71CzKHu4XNCw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CnIlLZxGVuh3lBUJqjPJEw==,iv:9EjO7S7EEBvkjAI/E9fcvgiwxJ6jI5L+j386vVFWBSM=,tag:2qbRU4UuE/LHY9ZFi+ceoQ==,type:str]
    namespace: ENC[AES256_GCM,data:7dRPqc6DqQhMuFd3mMUZQFI=,iv:cJ8e5I/RdjjXnU/EWQHwKeDs66KukxzhyhHo8GLOWmk=,tag:eW3ANeP9j6dlbD75OQfo5w==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:bWXPJP/Xhds/Lg==,iv:pYIn2OtcL3SYz0ifxLndzMZ6tAID+qwQBcRLHPv/2TY=,tag:Fon/zq90ffiPOffjhrijGw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:fH/PdYxxR8kwWJmUm0sAipzAEHVlaJmLhdwZKGZz6OtzLkuxnH1Y54iQ0MPsdkgF,iv:UArWqmcrBd6zIk0V3dpB58k0TbrpJ011RqBRZrcSDMs=,tag:azXXtuLuPHv3OuGhjPqHPQ==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSkptUThFSkRvVGkxUUJz
            ZlNzTkRsMFl5NDEvRUVSclNzQ3B5blkxUzB3CkdPUHpBOUovMW5PdlVSV2hPT0ZL
            MHhRUEVydGt6amMxaHp5SWpoRXQwYUEKLS0tIG5idHE4QzNDNGJ3bm1mNi9ic2Fq
            MjlrMndXb1FuTmtqb0pJNGIwVlhkZUUKRTL3szLQriST7Q9Cv+aUJ9nI5ICVi31U
            vmSc6f8YpfDBxaNuluvKNqD17dc0gMeCBAevaFNucPV+j2rBjOrzeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-28T13:56:19Z"
    mac: ENC[AES256_GCM,data:PI6Bj3TNjRm5wh+L/qwrDgy1SFdURtYHMcD6WUkdrlcRAY4y6dnCooCUBFvZKFRM1VbDf71qk7WfF+PXInKqkQPNVwWJ9GMYy3UgJR6Kl091m2umAIzS6i8JEShuCH3m1RmVmgXYu6HFt655IYrHvyfN9oxGANxlwPnTpVyPhmE=,iv:CkY9u+aDCKsLF16nSyAfPSBoV+0HuTTof/z9+C9LHfM=,tag:NkuVypk0JBHaDK2IE8WMzg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
