apiVersion: ENC[AES256_GCM,data:gWs=,iv:ZaHxTEtHvozJ7W9xbx2LulDVh4OUgteRPWTG0SY7FnM=,tag:P4sE9yaEnyGP7LOEzvTcHw==,type:str]
kind: ENC[AES256_GCM,data:wK1AKmvD,iv:JGpSiRgwdJHPl2ymlIDqo7d99tYDHaIfggca8CwHmV0=,tag:rJkoqyY4Aze3F3fcLxXusA==,type:str]
type: ENC[AES256_GCM,data:T2AU5JU7,iv:dIAzS8QjW6RSpfXTYynpvIUSlqhr3K+izoepVZDn4fQ=,tag:Ft0Z+5pEMf2cV/GRvTkPXw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wDS/vJMG8DSMugOIjVDtL3LPwiefPG12oVAFtg==,iv:+SN44+kgTfPXYUU64YxoDPmO3W/OtFby3sm1QQBk0JM=,tag:CcdnVO08CXsoLBxfZg9sSQ==,type:str]
    namespace: ENC[AES256_GCM,data:dhd+IE2tDA==,iv:3MKgKNR10Ux7lk/0v799c2qfN1XOYM52/4oiw4Rphr4=,tag:brZNtpYfenvEFdsejohr5w==,type:str]
stringData:
    terraform.tfvars: ENC[AES256_GCM,data:kQdlgbbr20iUcyzvyHXYOvY3S5UGiwQgzmFn50iheLweTgBa81txDvgDtmi7iJQbrFUDRryaGrfG8ZTTtmTFAkjwJvEVfE2vanHlAy8MrLQ6RLp8huPkL8aW1ufYRMQXFDyQV5b4UyxaR1coTuS0,iv:+79oBREhKgAuJkDQZZsu0hZQXyRYX/J6bUzod+fJC2A=,tag:ZaxreUaIbv7oALd7I88ahg==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYlVCajdQVzhLQzNhQ0FM
            MHRUa1B6NGtCZGREMHFERUJaeVl1SnpjcUhjCkFVbmlJZ1BnVjZhT0IxRGdqbjhS
            cHFMbXg5NHRqQVMwdE5DREdTcUpQcEUKLS0tIEpuWGhXM29HWWZnaXZsSG1BTUh1
            aW9sV3FtR0Uwd0JNN1I5OHYzYnoxYkUKXlMfaooIe/h8kvQDsmmH2E/0x4mps2mA
            MeN0Fhj/CUqykS+X7IJlSaPG6sdy60DPSVg1xqOYmRThI/jprMCiKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T13:07:16Z"
    mac: ENC[AES256_GCM,data:UOWn13C9Y/Y+3GM63vqcFAGhZxpd9fh0PqiscXK0FxYGc/+JXxOPUBAEmSklqCr5IW450nuJz481b7q7HoVAjWp7yu97FHrBeKBs5312Z4MJOtsI6PUeWE9pI8QpVRe1aNXNPtaNbuSuIS9eoNkbFP82Fw/YBfU18qIi2RslWRY=,iv:zzItdqr4TqfG0UiqI80tiMJaAPBvl0QFC4Cx43Iad2Y=,tag:mVcoxz0FW2Xcw1kiPrIsig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
