apiVersion: ENC[AES256_GCM,data:ul4=,iv:ldy9Dwah7HlrEZFw6eYsyIy3GNeor2PNzgCiQ37tokQ=,tag:Uke1HzQFc3kAyf8OcUaG1A==,type:str]
kind: ENC[AES256_GCM,data:N/MFaTHy,iv:TC3Dq/ut1jUcUKt4ldg6wdd18k01WY+E+HYbfHyenWQ=,tag:yPqYd+0dHPX9AKLdFPoT1w==,type:str]
type: ENC[AES256_GCM,data:U7KCE9qS,iv:/SSYhbqxCDLNxnYJ2sLwsW+2jQR3bBUTPIm9xsOonWo=,tag:IWLY5mPtWEEZisWGsWWIAw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IjNLSqzRYgmzPrQ98g==,iv:22QRfrgMZ7qj+emS3a2lc5Ty2NnKiaJMwVgHfa2hV6I=,tag:eahgCHSqEcfI3Tsp5CWKWQ==,type:str]
    namespace: ENC[AES256_GCM,data:oDvIGLtotg==,iv:r76omaVen4xH0nEzx3NgdUpwdrp2qgOH1b5pVRfpdZE=,tag:6Y7Nqg7uqN2C5j9YjZOtrA==,type:str]
stringData:
    terraform.tfvars: ENC[AES256_GCM,data:6GtDhihsDCFfH8mStAX7KbfoN7MaNBGcZiIz7yCSoKW0QcxvZUsWKkdAGmWkB46PtKbgfWG7CN8jz/zt9MGbce9ClQ81wwHVWepdWo0UnZnlFl8oMX/x5hpDlpgAFYT8tRHT5no1r5Ewhz2NJRHE,iv:o5WZywJiPO/g9IYceclri5JkAKke1Iv9NcidgC6Ny4Q=,tag:ev7ZotVC9GJQuV7ImQb3Ew==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndGxNOXhrRE8yd3h3aEFr
            emtHMnFkRGw3Qk5tdWZxTUpxemkzYnNiS1hnCnNvcGhCRHIvRWtPQVUzcmRtS2Rq
            cFd5T2RLSjNkNUxwZWYzRXcvS2NkSWsKLS0tIFl2bVpEV1dHQkhUWlN0bkY5Sysz
            UG9tUzdjaTQ5c2N4RG9CZE1HSE8zeXMKplbao7RChtyY6pmDC9N4/pyMUJ9pZKLb
            7gJ9UslcqZbhXFTJExEyq0Flovrz6I9wXNTv02wpddyuOBep9rJJUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T13:07:16Z"
    mac: ENC[AES256_GCM,data:YkkEkq7aGR5hXs0zMY5n/Fo+NOpCrtk5OVW3KcXFocpGxJfNbypKxQOg3cOUT2GC/gwD2rPLG12SHHjLCB0dN66fTGka9TPQMJcgf5kvLy0xWtsfCanTt77G5bRTwpJYH/iqV4tp3L19cegTuLKPNTPJh2c/EPMcpO1sGsKQjt0=,iv:4GcqLXeiJFIKJELkG5BOqoio3ICqYJTYsFks9LOlRCo=,tag:enKEXkT8rhCzNgrUj6vIuA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
