apiVersion: ENC[AES256_GCM,data:59k=,iv:A7wkTsxnGeIMFy+mGS0dH6NbrPqvOFZj5OkunPYULy8=,tag:0uN2+krSgzw79jq/14o2jw==,type:str]
kind: ENC[AES256_GCM,data:9VaVd4l5,iv:U+cQPw1qbC5rtqIAAYwG+FcCiuu/Tzo9u7oia3gJD2E=,tag:hT5gPt4MJoF+owwUJDBzCw==,type:str]
type: ENC[AES256_GCM,data:MxCU4Aml,iv:+KKhjltW1UPte92+gOtYGPmBEx9bV1yDR2Ex4lPadXY=,tag:NMRbNRgC3w40XOljA9uEfQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nLERXaM=,iv:eJygGXIwElGncvvaIWa9ti+JvDJZvYA9ovugrYwfLPM=,tag:8lmC5H+XZzczdwnlVGpgbg==,type:str]
    namespace: ENC[AES256_GCM,data:Z7ECxorhMuIL,iv:wwVWEIbMt6/nrXi+IFQzWhq1JkWWaK4NBiz/+cM5U0E=,tag:3klLivqDjcP7Zb2ehNQdAA==,type:str]
stringData:
    VAULT_ADDR: ENC[AES256_GCM,data:g9McNv8P97Itww5+uYgaMmuAa/QY62sEsM8jnfaTaK78g1Nb,iv:BDihq8I/mHwYrCuqHOyUIDFIlKOgxiq17kFFMmDZkSY=,tag:vrGNnwea9lVqZ/qQDBdCPw==,type:str]
    VAULT_ROLE_ID: ENC[AES256_GCM,data:fb5ST1JZ6mAtnvpnTUArVibT0w0uUcxxqsxPNxdz/97YYLBL,iv:7X0Npvyo9cWlZLtK5tkZ+0/ehSxi96Azz6GOC0oY3QU=,tag:Hr4sO7XrgNj3x8pWsoHLOA==,type:str]
    VAULT_SECRET_ID: ENC[AES256_GCM,data:VxBgk0M0BGQQniAVOfZq1wSuUZWImQwAULw0AvMo2xY2rb3x,iv:NAq6x9dUPFtFdqMadoD0kmRZWmEGxnHhIDsvD7gJ7oE=,tag:JHbP1yWPOBEw7UkLOyOlWg==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdktFU1dQNHNhemFoeXZY
            TmE3MzNQTUM1T3FrQ3BZTUtyYkw4V09BdzA4CkJrOWdBQ2F2SkxoVlh1UlpMN1Jj
            WjloUGxzQm4vME1xejRKNWNjeG40cUkKLS0tIEVkdFl3QUpud3hHZmt2ZjZDZ21H
            RDVDQUEvUEhWWk5FejQ0elVGby8yOXMKnHn9f/J7P23scoknNmnAsMzLS4gAwmcF
            N8VGf8kFSMuVydKW/uXCnYoYHeE0AdHbossNy152okSUyQSDXgDEYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T13:07:16Z"
    mac: ENC[AES256_GCM,data:+KQoQDEX9PRtD0HUzD7wjD7MdukP++6WmeDLxUyukbTba7YTqXIV0Oj/2aI1UWasO7mYih/hdbCDmby5AlLwWysYqmsBuJi800Wx0FJQ6F8t1Kcz+pa/3Z6kJ1wbvgDVmn0H5cw9ZaVe8d8xSlqxFMjmbt0G8H0F+ShrWuHRpvc=,iv:o+zxAWxzG277dHVA5BmJrQWxtqf+SIpStPFlZviYjeU=,tag:N4+Qv8JfftPj02nHj9zcsA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
