apiVersion: ENC[AES256_GCM,data:DXo=,iv:s+iCdBnLcIP/E7mX5q4m1L8nOE7YqFCkFDMIrhBNfLQ=,tag:ud235vPlCj/cj0zDOTIc7A==,type:str]
kind: ENC[AES256_GCM,data:hIwhuHbW,iv:KsuJoSIdNJxY+1mx2pi6iZGz40k+jF3NFFRT5Htr4Fc=,tag:xQd6zRP9zR1dSIQUpaeHkQ==,type:str]
type: ENC[AES256_GCM,data:rPsCUBDB,iv:D4Svr1BWtHxdXFOtKbuQSEYLQD60TxbERwGNJwBkN0w=,tag:EdkQhSmthMrojdHcD1hQYw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tGhX2S4b5lnIosY9zwPFops6Xh8=,iv:sluK7CZqKGrDrzKX08Tgr4xVXz2+Ed1iqX8lFCxVAoI=,tag:ENfbOIkg3RQAX+s5b6V3eQ==,type:str]
    namespace: ENC[AES256_GCM,data:M+dd4gtgOgoZ+wLqCKPXUM0=,iv:Di27GVR8W3ub12EyYc+OHNkLUurCTEsiXOuJjmEPKb8=,tag:vciYMWbGCL0925Nv/CmCTQ==,type:str]
stringData:
    credentials: ENC[AES256_GCM,data:jR3neiGpLMqvBaiom+jXvpaqJiIdZvwnLvBjX2WVH8u8t36tgjQ9xKMMuwyBP1U1YZVTcqFd7XJ2/pEpsnhHaSJATsSGjuMhmwQFbiUCXe0P0WAgGzCtnEwYszHDBxP2u5jOi4DLVk1nEyK1wfbEVPQJ2mmwW2NNK389sneqCupjijP+g6O4ximfMVSJvLJvYneRM1nsWM7BNubyhuOo+3QVVjpdzw==,iv:ZrU1I/urzA4ELO7NPb4I9BaEzVxCR2r7w71I/BTkFzk=,tag:Ak3wh1ZsYXmkd261vde+lg==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnc1l5V3gzQjg4QjNZakRv
            Q2QvdmUydE5tNG0yblZjenJaRFdKdU5RVjM4CkxGLzJBbnV4eDdjUVlKcXZZVHVZ
            L0hXOC9KOFhzZ2JNTkpucTVHNG53V0EKLS0tIExnYXN4TjhpaEYwbEFhNTdockt3
            L2gwa1JLU1lLY2h2VWdlM0ZSczZQZlkKtgQLhFjijwYuQEsk1oozekYhfV0A8uty
            ZIwj6kZsu8IgJeLWCHszFnMYahGvCV2J3HM18qyTjgWL2XNvq3MB7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T13:07:16Z"
    mac: ENC[AES256_GCM,data:kPPg4FFLH7DWRYjtJne5SMvLpAe7j+c/5AZWSWw5gRCZ2tU/eXBRiApQyrfvQdzu8ysdYvZ/zNyJR8g+HlOPgn/ceWHEIS6pp5Rp5lj5VkmHECoWcB3wpSEaKC0I0sxkmzI7MF0tsywh2r5/ByajKDi+UEwlqHno3vIIbkG9KhY=,iv:p51g684FbsJEpO+Jf2HuYWzA6m6cjEqFFwodGK+Q/ew=,tag:/NXAX7iCiGTeey6+bNxPhA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
