---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  annotations:
    managed-by: kcl-flux-kustomizations
    template: bundle
  labels:
    app.kubernetes.io/managed-by: flux
    kustomization.stuttgart-things.com/type: bundle
  name: infra-platform
  namespace: flux-system
spec:
  components:
  - '../components/cert-manager-ca-from-secret'
  - '../components/cert-manager-install'
  - '../components/cert-manager-letsencrypt-hetzner'
  - '../components/cert-manager-selfsigned'
  - '../components/cilium-gateway'
  - '../components/cilium-gateway-extra'
  - '../components/cilium-lb'
  - '../components/cnpg-barman-cloud'
  - '../components/cnpg-operator'
  - '../components/reloader'
  - '../components/trust-manager'
  force: false
  interval: '1h'
  patches:
  - patch: |
      - op: replace
        path: /spec/sourceRef/kind
        value: OCIRepository
    target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
  path: './infra/platform/root'
  postBuild:
    substitute:
      CERT_MANAGER_CA_FROM_SECRET_ISSUER: edge-ca # pragma: allowlist secret
      CERT_MANAGER_CA_FROM_SECRET_NAME: edge-ca # pragma: allowlist secret
      CERT_MANAGER_SELFSIGNED_ISSUER: edge-ca
      CILIUM_GATEWAY_EXTRA_DOMAIN: ${EDGE_PLAY_DOMAIN}
      CILIUM_GATEWAY_EXTRA_IP: ${EDGE_PLAY_LB_IP}
      CILIUM_GATEWAY_EXTRA_ISSUER: letsencrypt-hetzner
      CILIUM_GATEWAY_EXTRA_ISSUER_KIND: ClusterIssuer
      CILIUM_GATEWAY_EXTRA_ISSUER_KUSTOMIZATION: cert-manager-letsencrypt-hetzner
      CILIUM_GATEWAY_EXTRA_NAME: edge-play-gateway
      CILIUM_GATEWAY_EXTRA_NAMESPACE: default
      CILIUM_GATEWAY_EXTRA_POOL_NAME: edge-play-pool
      CILIUM_GATEWAY_EXTRA_TLS_SECRET: play-wildcard-tls # pragma: allowlist secret
      CILIUM_LB_IP_START: ${EDGE_LB_IP}
      CILIUM_LB_IP_STOP: ${EDGE_LB_IP}
      FLUX_SOURCE: flux-repo
      INFRA_DOMAIN: ${EDGE_DOMAIN}
      INFRA_GATEWAY_NAME: ${EDGE_GATEWAY_NAME}
      INFRA_GATEWAY_NAMESPACE: default
      INFRA_TLS_SECRET: wildcard-tls # pragma: allowlist secret
      TRUST_BUNDLE_VAULT_CA_SECRET: edge-ca # pragma: allowlist secret
  prune: true
  retryInterval: '1m'
  sourceRef:
    kind: OCIRepository
    name: flux-repo
  suspend: false
  timeout: '10m'
  wait: true
