---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-claim2
  description: Crossplane claim (volumeclaim) - test-claim2
  annotations:
    github.com/project-slug: stuttgart-things/harvester
    backstage.io/source-location: url:https://github.com/stuttgart-things/harvester/tree/main/claims/apps/test-claim2
    claim-machinery/template: volumeclaim
    claim-machinery/category: apps
  tags:
    - crossplane
    - claim
    - volumeclaim
    - apps
spec:
  type: crossplane-claim
  lifecycle: production
  owner: platform-team
