---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: harvester
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/stuttgart-things/harvester.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harvester-claims-cli
  namespace: flux-system
spec:
  interval: 5m
  path: ./claims/cli
  prune: true
  sourceRef:
    kind: GitRepository
    name: harvester
  wait: true