apiVersion: ENC[AES256_GCM,data:rEI=,iv:qvcqAInLyLWH3Kd6X2yqJTlC5kd8Fzsq3R6N0QAlU+E=,tag:Hvx7K5DxBicjJuODT4Eo9w==,type:str]
kind: ENC[AES256_GCM,data:L5QTri3x,iv:AiyFtWzZAi+5T+K80TGMvLDd08Pq+wYaKmh9NlhkJOo=,tag:mQEASQrcT9UG5yCClFkYTQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Nj1FgB4IMbf6ekogyRA=,iv:Wdey9eYHRBL1DKmdGwVaxXktzt0FJ/RVq3btS7/zjyU=,tag:sS6Pqxcd6dp+vKh911rgfQ==,type:str]
    namespace: ENC[AES256_GCM,data:EP33V3Y6cwBmfCA=,iv:YirSm9XXGiLwS+OAQQA/tw+kSdoiapNND8pCBJCPGXU=,tag:yRqWkHCZHlFXez1NIgKx1w==,type:str]
type: ENC[AES256_GCM,data:nrlLRn2w,iv:/kps2GVBodbXAIa1L0dbEim+kPxBPRrK0IQllQifv8Y=,tag:/bmiNPPKnGeUKC/GXiuG5g==,type:str]
stringData:
    username: ENC[AES256_GCM,data:DKBWQ79DoQdaoLjfCB0ZYsbpcg==,iv:oDFv/rXR2MzVKExeem0jDYx4oi2mLF7VjMVyrl/TeZk=,tag:zBujzRzcnFuiaSAqqcNXCQ==,type:str]
    password: ENC[AES256_GCM,data:/xQQveqdRNAh02Sg0hKhG1dR4l/J68q3zxo1A9gY3rj4dsC6TIXhmA==,iv:HKQobY6FolYCP8G4F063kOOu75A2VLldC9IFW6eNbNg=,tag:HiGQae5YEchpaQFpoFDRHQ==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OHcvbnhZdTBjZ3pwVzRK
            Y0VrK1FOa2N2c3ZUYXljK1hqYkJvVFVqY0ZFCnptWVBoRUcxckhCRlVGdzRxYVZB
            dmh0ZmluejJkZVdSZVdTT0tmblNIaGMKLS0tIHV4U01yMllwQVZjb0V4RXNQR1dq
            NlQ3R0p1VVRhOFFieHN2U1lRcEluSDQKij5ibJsSExf7baBnkh0GLHyIDxmehhy6
            2bXsKY6ssVqP/0mgVPuUL82mP2yjeLEGB5P2XfOThOtJuiHpI1JHoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T13:38:57Z"
    mac: ENC[AES256_GCM,data:NBrb1mkuEg3Q+22Knk9EscVdtttLpdol/wY9B7YayCfDlWtcD1efMgKRvI6VESIp75otsYbM3qiGK6x+BWXnKo6EQ+9SoOzhlCYtwNDvlaSxCxqibelrje7RXdUiGtdBLdquOF4i7NP+eUrqAVYMPasODdblX7XT2lNLvOaK8LY=,iv:E8aKpyy/a/Zo7bXHO2wwnnrUk56XLXaax8pOJMeh1Fg=,tag:flW1vsDY08kJvNnZyVB9Pw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:Grw=,iv:u/x0/+0LvkNKsCdWezHz1KBmHjMuwOhKubWwEizXwVQ=,tag:XfJhUgxjzeJYa1r39+efnA==,type:str]
kind: ENC[AES256_GCM,data:uz1NkzYK,iv:ArYEPQ029SDG+aqAs0PIDTc8ky7SHpM/TyhQujLVsF0=,tag:PeOQ++AlcN9+hDlM+XIs4Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XbzC8KY8i2E=,iv:4A6h4me62DTOqpOfqJu+66yS8RR7uEzKgp5JfLnFayo=,tag:4ywgWii38zCQHDK+MdWTyw==,type:str]
    namespace: ENC[AES256_GCM,data:PEhy2/n39uDvRVQ=,iv:Xfe97ak/8+3OGJcw5E+7ycrYGkHrwv2nXbgiVZ14ndA=,tag:B6wz48jOzxIm3XqoOpmheQ==,type:str]
type: ENC[AES256_GCM,data:vZd5x9u4,iv:mt12lO2eeVBhbeNl6dMeHjyb/Rt95wA3OU3M5b5tO9Q=,tag:olDw82jzJhYufU2DBj9A/g==,type:str]
stringData:
    age.agekey: ENC[AES256_GCM,data:Ctj7Ni61lIw9PQHCn/V5cwz8piJK3t1qvcTfXV2HBRPDk2IuKeb/DfE+2gIVd6j3b5W7jqxXGvhg5op8ew0bAj8HnmcSWIPVUHo=,iv:pLAQXoobEObKHxBpUG4vN4OGHo7C2dQDwbnadfcQKHM=,tag:kOvvlXzxf+YlMi2jb3viBA==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OHcvbnhZdTBjZ3pwVzRK
            Y0VrK1FOa2N2c3ZUYXljK1hqYkJvVFVqY0ZFCnptWVBoRUcxckhCRlVGdzRxYVZB
            dmh0ZmluejJkZVdSZVdTT0tmblNIaGMKLS0tIHV4U01yMllwQVZjb0V4RXNQR1dq
            NlQ3R0p1VVRhOFFieHN2U1lRcEluSDQKij5ibJsSExf7baBnkh0GLHyIDxmehhy6
            2bXsKY6ssVqP/0mgVPuUL82mP2yjeLEGB5P2XfOThOtJuiHpI1JHoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T13:38:57Z"
    mac: ENC[AES256_GCM,data:NBrb1mkuEg3Q+22Knk9EscVdtttLpdol/wY9B7YayCfDlWtcD1efMgKRvI6VESIp75otsYbM3qiGK6x+BWXnKo6EQ+9SoOzhlCYtwNDvlaSxCxqibelrje7RXdUiGtdBLdquOF4i7NP+eUrqAVYMPasODdblX7XT2lNLvOaK8LY=,iv:E8aKpyy/a/Zo7bXHO2wwnnrUk56XLXaax8pOJMeh1Fg=,tag:flW1vsDY08kJvNnZyVB9Pw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
