apiVersion: ENC[AES256_GCM,data:Grw=,iv:u/x0/+0LvkNKsCdWezHz1KBmHjMuwOhKubWwEizXwVQ=,tag:XfJhUgxjzeJYa1r39+efnA==,type:str]
kind: ENC[AES256_GCM,data:uz1NkzYK,iv:ArYEPQ029SDG+aqAs0PIDTc8ky7SHpM/TyhQujLVsF0=,tag:PeOQ++AlcN9+hDlM+XIs4Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Nj1FgB4IMbf6ekogyRA=,iv:Wdey9eYHRBL1DKmdGwVaxXktzt0FJ/RVq3btS7/zjyU=,tag:sS6Pqxcd6dp+vKh911rgfQ==,type:str]
    namespace: ENC[AES256_GCM,data:PEhy2/n39uDvRVQ=,iv:Xfe97ak/8+3OGJcw5E+7ycrYGkHrwv2nXbgiVZ14ndA=,tag:B6wz48jOzxIm3XqoOpmheQ==,type:str]
type: ENC[AES256_GCM,data:vZd5x9u4,iv:mt12lO2eeVBhbeNl6dMeHjyb/Rt95wA3OU3M5b5tO9Q=,tag:olDw82jzJhYufU2DBj9A/g==,type:str]
stringData:
    username: ENC[AES256_GCM,data:DKBWQ79DoQdaoLjfCB0ZYsbpcg==,iv:oDFv/rXR2MzVKExeem0jDYx4oi2mLF7VjMVyrl/TeZk=,tag:zBujzRzcnFuiaSAqqcNXCQ==,type:str]
    password: ENC[AES256_GCM,data:1MPmNnNLWRkXsgNFr4B3MfYPB+s6s4iztX2Sl0CbNzAOg/txhnGiIw==,iv:6Rsfsj5Yv0tCV1/TWDHhwt9pLcWIgBvl7h5kusw73G0=,tag:TckLHwpiIw77awOZ6fiPpQ==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OHcvbnhZdTBjZ3pwVzRK
            Y0VrK1FOa2N2c3ZUYXljK1hqYkJvVFVqY0ZFCnptWVBoRUcxckhCRlVGdzRxYVZB
            dmh0ZmluejJkZVdSZVdTT0tmblNIaGMKLS0tIHV4U01yMllwQVZjb0V4RXNQR1dq
            NlQ3R0p1VVRhOFFieHN2U1lRcEluSDQKij5ibJsSExf7baBnkh0GLHyIDxmehhy6
            2bXsKY6ssVqP/0mgVPuUL82mP2yjeLEGB5P2XfOThOtJuiHpI1JHoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-21T12:02:43Z"
    mac: ENC[AES256_GCM,data:nE0ZSy9NYCVTY8/64+BfcAR2VR8ByRBqOpakRQVZDomsQ76JCHgJiU2lDMGQ16zIQYKC0tqe8oUM/DfAnvSj2whT6y7wkbT44SEYHlVx6VTVOe8Xb+K75xOWEAwdlMDgZGZKWyl6lGMtJffAy8cmaiO8oGPeQ+RhQ+/oc1RGaxw=,iv:i/xtyPVlHnFLAGas4SSiWuFs+WsvRBtqUWrxBx57kLg=,tag:r+9VyUTvukEF7PdMvTauyQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:Grw=,iv:u/x0/+0LvkNKsCdWezHz1KBmHjMuwOhKubWwEizXwVQ=,tag:XfJhUgxjzeJYa1r39+efnA==,type:str]
kind: ENC[AES256_GCM,data:uz1NkzYK,iv:ArYEPQ029SDG+aqAs0PIDTc8ky7SHpM/TyhQujLVsF0=,tag:PeOQ++AlcN9+hDlM+XIs4Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XbzC8KY8i2E=,iv:4A6h4me62DTOqpOfqJu+66yS8RR7uEzKgp5JfLnFayo=,tag:4ywgWii38zCQHDK+MdWTyw==,type:str]
    namespace: ENC[AES256_GCM,data:PEhy2/n39uDvRVQ=,iv:Xfe97ak/8+3OGJcw5E+7ycrYGkHrwv2nXbgiVZ14ndA=,tag:B6wz48jOzxIm3XqoOpmheQ==,type:str]
type: ENC[AES256_GCM,data:vZd5x9u4,iv:mt12lO2eeVBhbeNl6dMeHjyb/Rt95wA3OU3M5b5tO9Q=,tag:olDw82jzJhYufU2DBj9A/g==,type:str]
stringData:
    age.agekey: ENC[AES256_GCM,data:Ctj7Ni61lIw9PQHCn/V5cwz8piJK3t1qvcTfXV2HBRPDk2IuKeb/DfE+2gIVd6j3b5W7jqxXGvhg5op8ew0bAj8HnmcSWIPVUHo=,iv:pLAQXoobEObKHxBpUG4vN4OGHo7C2dQDwbnadfcQKHM=,tag:kOvvlXzxf+YlMi2jb3viBA==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OHcvbnhZdTBjZ3pwVzRK
            Y0VrK1FOa2N2c3ZUYXljK1hqYkJvVFVqY0ZFCnptWVBoRUcxckhCRlVGdzRxYVZB
            dmh0ZmluejJkZVdSZVdTT0tmblNIaGMKLS0tIHV4U01yMllwQVZjb0V4RXNQR1dq
            NlQ3R0p1VVRhOFFieHN2U1lRcEluSDQKij5ibJsSExf7baBnkh0GLHyIDxmehhy6
            2bXsKY6ssVqP/0mgVPuUL82mP2yjeLEGB5P2XfOThOtJuiHpI1JHoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-21T12:02:43Z"
    mac: ENC[AES256_GCM,data:nE0ZSy9NYCVTY8/64+BfcAR2VR8ByRBqOpakRQVZDomsQ76JCHgJiU2lDMGQ16zIQYKC0tqe8oUM/DfAnvSj2whT6y7wkbT44SEYHlVx6VTVOe8Xb+K75xOWEAwdlMDgZGZKWyl6lGMtJffAy8cmaiO8oGPeQ+RhQ+/oc1RGaxw=,iv:i/xtyPVlHnFLAGas4SSiWuFs+WsvRBtqUWrxBx57kLg=,tag:r+9VyUTvukEF7PdMvTauyQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
