apiVersion: claim-registry.io/v1alpha1
kind: ClaimRegistry
claims:
    - name: abrechnungen
      template: volumeclaim
      category: other-resources
      namespace: default
      createdAt: "2026-02-05T17:45:56Z"
      createdBy: patrick
      source: backstage
      repository: stuttgart-things/harvester
      path: claims/other-resources/abrechnungen
      status: active
    - name: hacky
      template: volumeclaim
      category: cli
      namespace: default
      createdAt: "2026-02-05T10:58:33Z"
      createdBy: patrick
      source: cli
      repository: stuttgart-things/harvester
      path: claims/cli/hacky.yaml
      status: active
    - name: harvestervm-developer-martin
      template: harvestervm
      category: cli
      namespace: default
      createdAt: "2026-02-05T17:57:18Z"
      createdBy: patrick
      source: cli
      repository: stuttgart-things/harvester
      path: claims/cli/harvestervm-developer-martin.yaml
      status: active
