apiVersion: ENC[AES256_GCM,data:YoU=,iv:s3weFkXwFuNrE56T69hV6ASowRxAb5h84l00dBz1Z3I=,tag:p6DybXV12EYYNbTrgSkRqQ==,type:str]
kind: ENC[AES256_GCM,data:TLDi2qmO,iv:zCtvsEFikqSapJcPr7ri6sOOkF662dEHsbrJMT0vdPs=,tag:HYIETTws/FrqLMs0cy/rmQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vEkijV1I0m8T7hIjBUk=,iv:xFycvvYTFS6jVkmB7LpnYlb4xGsuyIcAmoQ95nT0dls=,tag:9qOQatN/Ncrw2SmU4qeuLQ==,type:str]
    namespace: ENC[AES256_GCM,data:Qzv7Onfx4h3h6qo=,iv:yUp0noq6eKwfhX5QWaZ2mhHAPCYIsD1y8keaI17xNVk=,tag:xpRGSkDvXm9+xDnKznO2ug==,type:str]
type: ENC[AES256_GCM,data:K/CE4e5F,iv:dWQhokRn8804r3K+Il+GH0Lr/f0CgTDv22Q/lvNBLiA=,tag:ETnTHA4DOS0Cz3XGWjTZFw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:nIvvAQaRNPe48Yt6EYMykhH27A==,iv:bQ9wFZ0hI8G73xscsFasIg9hplznR30dqPZG4k1aGeo=,tag:2I7lZtl0d0zK9cfAjz/mFQ==,type:str]
    password: ENC[AES256_GCM,data:PuHy8L0aq6/jQkvaJeRGw3sgdwHc5TEkvkLkNFcqBcnNrtC7o6fjXA==,iv:S8i5MpnoBxOp3qQGg7Tc2OSkZ4zAQiAeMYwfDLAJXyo=,tag:y4pLn4Bgzsf1C/8j6LLO8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbXhjaDlkY21EczlmaGtm
            NWpwcFVkbTdWZUF4Y3J3WUVON1krRnhWOW13CmRBNWxmMFNrRUgzZDJ0SWpCMitB
            bWI1Y0xGN3lOVW40Qm5nd1lIZi91alkKLS0tIDZXYlRLa3RPRElNblVjSjYrVHRY
            NERPOURvRkxIa01RSSt3by9ycU5JUGMK0ym7n9gTEd7TzoJlO06eg2Ex1kjLaAf7
            DXKMKs/ck3OMC++A/wTj95HSdyos291DygJrHGLcSr2Yla0/1IdXkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
    lastmodified: "2026-10-03T10:58:56Z"
    mac: ENC[AES256_GCM,data:K3SYIykrxx6jFIZkDjGOCITsYVkzct/1h5O1H8mS7shNhBCpuVvSlIZU2M6fYt6SXHnGkJVJarg+QswkbDjnhj9xuJZuhCStEK3DM3uzBJ7DAbSvzwMmnq04/xNf3BexOaJzDUgG+AXjznWs/Bh6qDsSn8TgWlWqrnYg5oG7vrw=,iv:JR4DOyWBBGTnH4YvVgUF/RWdrO/1cUQt0AlBk6LG5Co=,tag:W74ycinVUj3GsL2dKj7TLA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
---
apiVersion: ENC[AES256_GCM,data:IpI=,iv:VEXJlsHcsKDr+WH1lqr/sNRFtir16JePuTORocT+faQ=,tag:djN6CLzR5u4AmvgQr03jTA==,type:str]
kind: ENC[AES256_GCM,data:R+sYUE+f,iv:RsLVFs+N9GXfYrJGk5yA8f/CCyawVQ2QocfIsTTVcXg=,tag:mkiXxKNGphoPAGD3yMlLTg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:v0S8Wcsuiew=,iv:JcFRx8G0dt4hTHaEHcpyUyTucuC40Ddy2DwmQkXGKv0=,tag:LR8AylQs9umMqKHbTba01g==,type:str]
    namespace: ENC[AES256_GCM,data:ocXlhmh8jp18auU=,iv:KTRlkL1xPKN8OJXdozF0Q1A7xLIv+Pj1z+65V8SkfsM=,tag:NByYcFlOWhroc4N5kLOy0Q==,type:str]
type: ENC[AES256_GCM,data:/XLJzm+l,iv:6PmkAZe6hj860mD0CUllV6CKhPyXROKjbHROJnfHlGQ=,tag:anzMrZAekzMnh6T/D+qQeQ==,type:str]
stringData:
    age.agekey: ENC[AES256_GCM,data:Av02zE/TWNHZe1i2NaYlMicysk3gxnuU4JrO/t6VBWxdQmzvTN7bREmeGq4KOWQmj++cQTdc6yfC2Io9iLraFBM0awKqZGMhMsY=,iv:GTeyR0Y3ZXEAw5PMWQnNHiCh0z37QSB6AIkaJwbRTM0=,tag:bCIxc43R30mpicKS0HCgrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbXhjaDlkY21EczlmaGtm
            NWpwcFVkbTdWZUF4Y3J3WUVON1krRnhWOW13CmRBNWxmMFNrRUgzZDJ0SWpCMitB
            bWI1Y0xGN3lOVW40Qm5nd1lIZi91alkKLS0tIDZXYlRLa3RPRElNblVjSjYrVHRY
            NERPOURvRkxIa01RSSt3by9ycU5JUGMK0ym7n9gTEd7TzoJlO06eg2Ex1kjLaAf7
            DXKMKs/ck3OMC++A/wTj95HSdyos291DygJrHGLcSr2Yla0/1IdXkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
    lastmodified: "2026-10-03T10:58:56Z"
    mac: ENC[AES256_GCM,data:K3SYIykrxx6jFIZkDjGOCITsYVkzct/1h5O1H8mS7shNhBCpuVvSlIZU2M6fYt6SXHnGkJVJarg+QswkbDjnhj9xuJZuhCStEK3DM3uzBJ7DAbSvzwMmnq04/xNf3BexOaJzDUgG+AXjznWs/Bh6qDsSn8TgWlWqrnYg5oG7vrw=,iv:JR4DOyWBBGTnH4YvVgUF/RWdrO/1cUQt0AlBk6LG5Co=,tag:W74ycinVUj3GsL2dKj7TLA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
