apiVersion: resources.stuttgart-things.com/v1alpha1
kind: HarvesterVM
metadata:
  name: kai-vm
  namespace: default
spec:
  providerConfigRef: harvester
  volume:
    pvcName: kai-vm-root
    namespace: default
    storageClassName: harvester-longhorn
    storage: '80Gi'
    accessModes:
    - ReadWriteMany
    volumeMode: Block
  cloudInit:
    vmName: kai-vm
    namespace: default
    hostname: kai
    domain: stuttgart-things.local
    timezone: Europe/Berlin
    packages:
    - curl
    packageUpdate: true
    packageUpgrade: false
    sshPasswordAuth: false
    disableRoot: true
  vm:
    runStrategy: RerunOnFailure
    evictionStrategy: LiveMigrateIfPossible
    terminationGracePeriodSeconds: 120
    os: ubuntu
    machineType: q35
    cpu:
      cores: 8
      sockets: 1
      threads: 1
    resources:
      memory: '8Gi'
      cpu: '8'
    disks:
    - name: rootdisk
      bus: virtio
    - name: cloudinitdisk
      bus: virtio
    networks:
    - name: default
      networkName: default/vms
