apiVersion: v1
kind: Secret
metadata:
    name: openbao-static-seal
    namespace: openbao
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:HnPbtJ0DbQOUh1myWsxYGSKgKlWS13pRwGicS7yz46uOHUwDodqY6AinJN4=,iv:6HSYsmdRb2noaGm/UEHIHujIgl5HkVMc0IUw02MniV8=,tag:M0eS+0q+RZ2x60jSGHn/AQ==,type:str]
sops:
    age:
        - recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITmUxWXQ5b2J2YXJaUmNs
            b0QxT1VzNEFMYkdZWjNnT3NjMVMycFNwWEc4CnRmY0h5VUg2TXBndVlESjlTdUs3
            VTcxWnpWME1lK2RrUjVOQTVlamlOcjAKLS0tIGZoamN5dTk5U042aTdhUDRpay9i
            QWFKaDlrTkJySE4weTBqY3JDWExoQWMKugz79XkHqoitkK0zNh4A3anYsbwhZ0TR
            zWnZuFeYjds2tGUoq6xJYdAKrh61pVXFGcm0Lq/wR/VOX+DlITpgEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-04T05:18:07Z"
    mac: ENC[AES256_GCM,data:8sJMi2RoV2oYggnOfxRk0kTA/Fo6YbFp8N5yaBri6uMvxla9UV/FHpKp+I+QbWVhwqmyeVKYV3QaC5YtvWbGxpkDgBhUphsWqT/ZI1Hs9OhOxZ/0Y2y0aHnIsCfdwuj70xbEbHicJkshqI8UYvC/PkRF9BNMlzuHPh1a6Lk8CFo=,iv:p4LIN0S849HkOK3/PoFEdiJEz3xwdBHtco2HiZZITHs=,tag:9JAyVtGFOrYNM24G6paAEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
