apiVersion: ENC[AES256_GCM,data:tOU=,iv:0S9p0uvtQPa0LNpbBGCC4BJBgwZiaY4qjFxFENXecbY=,tag:p4MJiJbTqon7IX35kpssRQ==,type:str]
kind: ENC[AES256_GCM,data:Lzyog1tj,iv:0YwAypXpULpeDkrtTQiYOluC0m/RgS0HvRR7p8NTpTI=,tag:4M+EvBRP5GZyLYDdjCgqtg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:K81wjEbPVRPvAGsjiKI=,iv:QJr9jjJ/+PT44csbIWLK24mI9MJ7Yl/NWpTtUzO0cVQ=,tag:R2hpO52onel3dmbQDECZ+g==,type:str]
    namespace: ENC[AES256_GCM,data:H9xmn66aH2vP8gc=,iv:+gx7h3wv5cPBvl5N/ZKy9sZ0D4X6zA8O9SFehgzfMzI=,tag:42Uer+M2fDAkqCukN4YR7w==,type:str]
type: ENC[AES256_GCM,data:53PM7clj,iv:5Apf9z+TclX52JZ8RbSCL23HGRWwg7T3VMwvX0fN888=,tag:fokc4+V9doEdtpJ0+2A9Og==,type:str]
stringData:
    username: ENC[AES256_GCM,data:YmUCslMqrtyk2PrzyIXg4qRlRA==,iv:aKJSC9n281KJeJCXWs90KouLhV79Lm89CvAShHk7C/8=,tag:4WPN7zAWmvdyIEYbRzC3Uw==,type:str]
    password: ENC[AES256_GCM,data:4WUO2I5eq/Urjx8E6qpQhkaSbi3s+TjJZ8GmWhmk/rTIputPV0+nhQ==,iv:IJH7/Y8Bw4daExq7jVXiSBQiQ3Hs2yj3i8mM4l76q+A=,tag:a5Z0QgU/2Rkgv90sA+W7/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3R2V2L0xwamdiMERSUitk
            RFJucjA1RVhUOW5QYXpQZStRNWRpVGtsVlg4CmpJNVIxTmtlZ3NmdmlheVNadHUw
            aTJMdUk2L2djckhQNmxBYTFiQzBoSG8KLS0tIFl0NGFaSDYwZGxuWlRHVHNhOEx6
            Y3lwNTRrOXI0aWpSbENDckgyT09EQ3MK0G0PPQzhhEHKtA9aX3NtfUgVyvWtOBzf
            q6aH5i4AoUjwrOD5Sd1pxrVGYAmWQMNp87BvyWddH4kTtJRfi5XiWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
    lastmodified: "2026-09-24T12:35:10Z"
    mac: ENC[AES256_GCM,data:A/By5dL+bYO7Kd/N6C0SAmkwhpUo9KfbCyVRa78RJOcDgt+Q0QMlMLkyyASD4o9ccxCarBHWtXYtg/0YEn9G9CG2HMKE/lkse9gyT+OJSkUJ5n1dmwTzDB9uGHlZ5U1Xyu0uwbzzSdegycc9MFojvbJFHHscuxA1w2FzGUFGoB8=,iv:Ql3EDLUFNwTt1HyqLTvrDl73QEb/arSwLmMlUv594Oo=,tag:EpzyYh7zq7JDkkqXv/nAUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
---
apiVersion: ENC[AES256_GCM,data:epg=,iv:BdXl7i+XvM8wU+6wqa/l47V2DnUhM9xU4JHl2g1KRkk=,tag:SNc4nv45fMnNvfgaRed5Cw==,type:str]
kind: ENC[AES256_GCM,data:Q6dL6uBt,iv:3i5m/Lkq1aV3YolvpNTe36JNNyZ5w+mCz6/Me20GId4=,tag:rGJ4dUdTBbnaXTqap7B7HA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XfZhZq+k5Jg=,iv:hCKd4p6omj6TZT7Zis4RYu+yiSO2J6SbFk5LuqGKXOg=,tag:+sa7CTS8PmaJ7xkEQV4fpg==,type:str]
    namespace: ENC[AES256_GCM,data:pglrW9+kABvAgS0=,iv:VPrRLP3FRYfgsgMFopx1deNZrdMjan8ur+L2J4cBk3E=,tag:tfjw4jB/SqxupEUOcmIzgg==,type:str]
type: ENC[AES256_GCM,data:dA6U+AXY,iv:30zXu4Qb4nW/LN02Ih3V2Xo2sst/jyHnV8U296eI7xQ=,tag:vTs0ydyM94Tuqm4dS6PNTQ==,type:str]
stringData:
    age.agekey: ENC[AES256_GCM,data:CRMRSn/x/iJx4l5LghZfy90uPijQjAoSqUVbngMoi73fWt8/C9LEYeiF2unzCYQsQaiibfFHGbn9SxX7M9UVQ5My8grSmOJv58U=,iv:6sDxW86oJK0QYKyqND3X7xje6MHyp5fjOtMWtoAa7Vs=,tag:7HJJmbOsD0iwLGY75YrNtw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3R2V2L0xwamdiMERSUitk
            RFJucjA1RVhUOW5QYXpQZStRNWRpVGtsVlg4CmpJNVIxTmtlZ3NmdmlheVNadHUw
            aTJMdUk2L2djckhQNmxBYTFiQzBoSG8KLS0tIFl0NGFaSDYwZGxuWlRHVHNhOEx6
            Y3lwNTRrOXI0aWpSbENDckgyT09EQ3MK0G0PPQzhhEHKtA9aX3NtfUgVyvWtOBzf
            q6aH5i4AoUjwrOD5Sd1pxrVGYAmWQMNp87BvyWddH4kTtJRfi5XiWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
    lastmodified: "2026-09-24T12:35:10Z"
    mac: ENC[AES256_GCM,data:A/By5dL+bYO7Kd/N6C0SAmkwhpUo9KfbCyVRa78RJOcDgt+Q0QMlMLkyyASD4o9ccxCarBHWtXYtg/0YEn9G9CG2HMKE/lkse9gyT+OJSkUJ5n1dmwTzDB9uGHlZ5U1Xyu0uwbzzSdegycc9MFojvbJFHHscuxA1w2FzGUFGoB8=,iv:Ql3EDLUFNwTt1HyqLTvrDl73QEb/arSwLmMlUv594Oo=,tag:EpzyYh7zq7JDkkqXv/nAUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
