---
apiVersion: github.stuttgart-things.com/v1
kind: NetworkConfig
metadata:
  name: clusterbook-networks
  namespace: clusterbook
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/reconcile: disabled
spec:
  networks:
    "10.31.101":
      - "5:ASSIGNED:rancher-mgmt"
      - "6"
      - "7"
