---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: suse15-dev-packer-image
  description: suse15-dev Packer Image for Harvester
  annotations:
    github.com/project-slug: stuttgart-things/harvester
  tags:
    - harvester
    - packer
    - opensuse-leap
    - users-customized
    - packages-customized
spec:
  type: packer-image
  lifecycle: production
  owner: platform-team
  dependsOn: []
  profile:
    addedUsers:
      - hans
    addedPackages:
      - nginx
      - vim
