---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xplane-disk-0
  namespace: default
  annotations:
    harvesterhci.io/imageId: default/upstream
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: '50Gi'
  storageClassName: longhorn-upstream
  volumeMode: Block
---
apiVersion: v1
kind: Secret
metadata:
  name: xplane-cloud-init # pragma: allowlist secret
  namespace: default
type: Secret
stringData:
  networkdata: ''
  userdata: |
    #cloud-config
    hostname: xplane
    ssh_pwauth: true
    users:
      - name: sthings
        sudo: ALL=(ALL) NOPASSWD:ALL # pragma: allowlist secret
        lock_passwd: false # pragma: allowlist secret
        shell: /bin/bash
        ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC...
    # Set password for user
    chpasswd:
      list: |
        sthings:Atlan7is
      expire: false
    package_update: true
    packages:
      - qemu-guest-agent
    runcmd:
      - - systemctl
        - enable
        - --now
        - qemu-guest-agent.service
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: xplane
  namespace: default
  labels:
    os: linux
  annotations:
    description: xplane-vm
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      labels:
        vmName: xplane
    spec:
      hostname: xplane
      domain:
        machine:
          type: q35
        cpu:
          cores: 12
          sockets: 1
          threads: 1
        resources:
          limits:
            memory: '12Gi'
            cpu: '12'
        devices:
          disks:
          - name: disk-0
            disk:
              bus: virtio
            bootOrder: 1
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - name: default
            bridge: {}
            model: virtio
          inputs:
          - name: tablet
            type: tablet
            bus: usb
        features:
          acpi:
            enabled: true
      evictionStrategy: LiveMigrateIfPossible
      networks:
      - name: default
        multus:
          networkName: default/vms
      volumes:
      - name: disk-0
        persistentVolumeClaim:
          claimName: xplane-disk-0
      - name: cloudinitdisk
        cloudInitNoCloud:
          secretRef:
            name: xplane-cloud-init
          networkDataSecretRef:
            name: xplane-cloud-init
      terminationGracePeriodSeconds: 120
