---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: u25-dev-packer-image
  description: u25-dev Packer Image for Harvester
  annotations:
    github.com/project-slug: stuttgart-things/harvester
  tags:
    - harvester
    - packer
    - ubuntu25
    - users-customized
    - packages-customized
spec:
  type: packer-image
  lifecycle: production
  owner: platform-team
  dependsOn: []
  profile:
    addedUsers:
      - hans
    addedPackages:
      - apache
