apiVersion: resources.stuttgart-things.com/v1alpha1
kind: XVirtualMachine
metadata:
  name: workshop
  namespace: default
spec:
  size: large
  provider: harvester
  environment: harvester
  os: sthings-u26
  ansible: true
