---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vm-demo-morgen
  description: Crossplane claim (xr-virtualmachine-harvester) - vm-demo-morgen
  annotations:
    github.com/project-slug: stuttgart-things/harvester
    backstage.io/source-location: url:https://github.com/stuttgart-things/harvester/tree/main/clusters/crossplane-mgmt/xrs/virtual-machine/vm-demo-morgen
    claim-machinery/template: xr-virtualmachine-harvester
    claim-machinery/category: virtual-machine
  tags:
    - crossplane
    - claim
    - xr-virtualmachine-harvester
    - virtual-machine
spec:
  type: crossplane-claim
  lifecycle: production
  owner: platform-team
