apiVersion: resources.stuttgart-things.com/v1alpha1
kind: XVirtualMachine
metadata:
  name: vm-demo-morgen
  namespace: default
spec:
  size: medium
  provider: harvester
  environment: harvester
  os: sthings-u26
  ansible: false
