---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zeiss-smt-mittwoch
  description: Crossplane claim (xr-virtualmachine-harvester) - zeiss-smt-mittwoch
  annotations:
    github.com/project-slug: stuttgart-things/harvester
    backstage.io/source-location: url:https://github.com/stuttgart-things/harvester/tree/main/clusters/crossplane-mgmt/xrs/infra/zeiss-smt-mittwoch
    claim-machinery/template: xr-virtualmachine-harvester
    claim-machinery/category: infra
  tags:
    - crossplane
    - claim
    - xr-virtualmachine-harvester
    - infra
spec:
  type: crossplane-claim
  lifecycle: production
  owner: platform-team
