---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: apps1
  description: Crossplane claim (xr-rancher-cluster-harvester-bootstrap) - apps1
  annotations:
    github.com/project-slug: stuttgart-things/harvester
    backstage.io/source-location: url:https://github.com/stuttgart-things/harvester/tree/main/clusters/crossplane-mgmt/xrs/infra/apps1
    claim-machinery/template: xr-rancher-cluster-harvester-bootstrap
    claim-machinery/category: infra
  tags:
    - crossplane
    - claim
    - xr-rancher-cluster-harvester-bootstrap
    - infra
spec:
  type: crossplane-claim
  lifecycle: production
  owner: platform-team
