---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ansible-run
  description: Crossplane claim (xr-ansiblerun-minimal) - ansible-run
  annotations:
    github.com/project-slug: stuttgart-things/harvester
    backstage.io/source-location: url:https://github.com/stuttgart-things/harvester/tree/main/claims/infra/ansible-run
    claim-machinery/template: xr-ansiblerun-minimal
    claim-machinery/category: infra
  tags:
    - crossplane
    - claim
    - xr-ansiblerun-minimal
    - infra
spec:
  type: crossplane-claim
  lifecycle: production
  owner: platform-team
