apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-letsencrypt-hetzner-secrets
    namespace: flux-system
type: Opaque
stringData:
    HETZNER_DNS_TOKEN: ENC[AES256_GCM,data:Y6WLoPPSa63JivQVOnTnaSdmr7mdn42fRvKlkLkVu9iLbbxvw5DRxwQtrVsqXnxDcXiD1sRyPiOTKdorY9Q3GQ==,iv:pfRqbwCIkzvVXZm84SBes7S+ik/FKCBu0+9ZqQO4YvI=,tag:mOnXtcm2Ok1LGZbP5FPcnw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWnpCek1kOFczVmZvbkF5
            QldrbmpZb09CSnNJVlFmamdPenl0cGpsaHlNCnlUMkVDLzZMOFoxNERnZHA4WVpB
            NGhjMWlKQUZmTUdrNklFakxpWWF3amMKLS0tIEtMSFVKTEdYaFErNG4xUDVXRlhV
            a2JhOVhYcjZmZFd6OURuSDcwbWNVQm8KRUVAx1FNxgxgrmAdGcHSDJnEqKB+FL3/
            gd13ybrnCqgGdKbE60IvtKBb681nUzE0eoBPmcCxZ4NW6aynOXe37Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n5eqcd3nhuqmvg2h02c0wl2mpyx7tm62payw6ed2txnf7aevp9wq9wxue3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuU3BkRVVaa1hzQ1ZWR29i
            OXRtYUlScjFEbUx5dnpTZTNCN09GNVV0c3hFCjhjeEV1UlJBUE5NL3RDYzluNEpG
            SUhPSm50eWJPZURKRDhnUEIyTmxVME0KLS0tIENWd01TczVKZGd0N2l6YmNudDll
            SFFGVjZSOUxwbkl6b3ZuVTROZmxLaWMKtPRzBifSD6qBlvSorsLywpHT47PvWbBc
            tSE3Frf7OTSkoyxK2oBbjSACTmxJqvbmTZAxXomrZxtQjrxkkC0hBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T16:57:51Z"
    mac: ENC[AES256_GCM,data:L1pkkXCKeXyohdrwmQ4OtozHm4OFl11RfCXXzvMhQkSVCrDnry+3QEROr7ZbtU7NRLGy9fpA/1HdzwFWCnNs3uSbsMDLsuZTdeBofmH8HAFmVOApaLIs6Kn1L8a1mpRU1e3sKzRzRRmoiMFuIZbXmPSV1k2pAqfchauVPNA3QrI=,iv:APyc81rjzh2pTkIODrHNEe2n0Uvvdk88tk5tfApF1OI=,tag:L7M6cIUtwlK71ZP15XJFiA==,type:str]
    version: 3.13.3
