apiVersion: v1
kind: Secret
metadata:
    name: homerun2-sops-secrets
    namespace: flux-system
type: Opaque
stringData:
    HOMERUN2_OMNI_PITCHER_AUTH_TOKEN: ENC[AES256_GCM,data:PaETjXKn5TbhFJIMfhGjlT8Os/5oVwdmVd6xdFnEJ4RaP4RGO31qgzX7kwqZfPPN,iv:618CltkTphwyT5aB4csu92etGAePOvwNKGu+XZ8do1I=,tag:ZaP1Dn5dPB89x75YBBDmbg==,type:str]
    HOMERUN2_REDIS_PASSWORD_B64: ENC[AES256_GCM,data:ETOQIoVBu6tI2qqxMSwhHN0Bz9gur3QUo9bavZ3kFZmD8nGz7gOdkInXOTccTf5U0bCgphljakEH3sr5LajOFA==,iv:xWA08lvPz807jKa6Ht1c/EA6thKJQwQvxcZ2b3Z0PCM=,tag:oZYREUURLqU4D+oS+SG8TA==,type:str]
    HOMERUN2_SCOUT_AUTH_TOKEN: ENC[AES256_GCM,data:U2Kw+WKkmbse7IxR5n7vtSEaJB9l2g1QT4rwF2+azMwpRUNynYrpoIAW2hpNwz0C,iv:ziAru8RNBBaMfs7HjpoBWNfxooSumMhp4Y+do7So3VY=,tag:uR2r/YZ4MQUwWJmxsMCFRg==,type:str]
    TEAMS_WEBHOOK_URL: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TjJkSUhwNHF6c3RqM1Uz
            RnB2KzhKd3dMc0RXdUh0Zkg2SU9GenpZYTNNCmNBb2o1RlViTGxoaVNlMG1hQXly
            V29UcXdCc2lGdUU1NXFSVGhveVZ5RWMKLS0tIFgvNDh4UlM1SHFGTWRZbHE4Ly9n
            SUdOV21JRUozekZUS1NpWGJWV1VYVFEKX1iwfszQDygYMUGIBtNp3d0G0r2O/x8b
            Rl3tRL7s0uQYU43LBiTcwunIvcxs0Lm4qDaasMX0Nh23K3cLs3NycQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n5eqcd3nhuqmvg2h02c0wl2mpyx7tm62payw6ed2txnf7aevp9wq9wxue3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoM1hjNnhwNVZWYms4RTdo
            dGJlWDRYQ1pvbGdsdzQ5RUNHcU01ZVZqNHo4CmllUHcrTXJzdkdzZXp3TFhtMDhQ
            VnQ3QVE3VXRGTkdCai9kNjVMUjhYSkkKLS0tIE9TU0pEdW9KZDd0L0Vvc3ZieU5U
            RWpGeWRxYUtnSjN1YmpMVjh0SEt2WlUKKBicE6WOWj0OEnElgqrI+d243xINrVe7
            L524qmCkdrtSnYr7apQUrMy08TqvI8iJXg6raYtEzmxzw9t4Vd6R0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T05:08:06Z"
    mac: ENC[AES256_GCM,data:S7KCQHojdg4bRSBHJn9dzijS6XlRsglTmmV9hgUYF4hZwF1yFyjKlflg8atEQxODXi1Gn/lRoZhRyKlngN8i0JtbNX59CAtTJj49zv5PY8OV/Q2qg952dyS5VZFCJyoOyqjffXMYJFHSaolN6lBNE/Xi669CFfGBUoTIQ4OQ8CA=,iv:w1WmlHJRNFbDFG2vNqXCuP8wS2qxCuv8nIK4AK5MNXs=,tag:lXkBFuJ2xjNt9TvOfFqoow==,type:str]
    version: 3.13.3
