apiVersion: v1
kind: Secret
metadata:
    name: homerun2-light-catcher-tabletennis-sops-secrets
    namespace: flux-system
type: Opaque
stringData:
    HOMERUN2_REDIS_PASSWORD_B64: ENC[AES256_GCM,data:cH8N5Yym+oAYACHYlUG0iQfTpHvBI1JIcaAgx+8vvCqcELRbmfpdqYonkuF8My+OUsPRHo92aGAPg/kKTT9lLg==,iv:1qAr/60J0SAsaPMrbDo9ctLMxOAQODTkk64k271vUg8=,tag:nTEf3hyCEWNn2sPz45yDSA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYeTd6REpuc0dDY0hFTzRh
            c1NIN3V4QXBnbk9SMVRHc0ZKdUtjY2tUaHc4CnpIbS9iRHpUZkR4cFIyMExQRmRY
            SFRjcVRtekNOT0hVK2hwaGp3VFRZWGsKLS0tIHBJVm81TFVUb2RpNkpENE9KZ2FZ
            VHNOYTE0Q3RycFVudy9zRWhZZWNuck0KoRSXO7iLWCtRJgIoSFSed0xJvAsD6EJv
            w0ZFxewt8k9KVwN2R+13R90DxmVG4aLeWkJUADspWKVptkQ5qAHJyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n5eqcd3nhuqmvg2h02c0wl2mpyx7tm62payw6ed2txnf7aevp9wq9wxue3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnS3YwYnI1d3YvOS9qUVVy
            OUxQbVJ0aGMvU3J6by8wQ05DZUg5aDJZcmxjCkpHbnduS0lHcDNWUnZDZmxMeTZa
            cFhBY05hMDN4YnVCYWJ1bXl1YnpSQlEKLS0tIGVDVTNMaVFXdmtrN0RWczNjcFky
            OWtyOHFoeUE0cDZqUkRIdVFXaHhvdXMKNYHv490CLm9jWICvNSw0ITtW6wML+BJQ
            XPMyU8X+bVxiQFK5rR4PSdUJpFm8sBrG9G74wBg4slorm25enAIMHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T09:43:12Z"
    mac: ENC[AES256_GCM,data:+jSpyXzHXjHGJ23QhQbm25YGmkJ7ZCz3UEnE5cQ8g5ILOoscnUQ/EVExeMmkQn6Rzw6plPzQeqxpe0WMsCVcZEviWYKbRWKCW2qiCI95zSfs7OwQPoETVutpMHJ7q7u63i0wPMSzCKEvN6HEoRQVpdhZaTyWJTCtR+tIsQqpAK8=,iv:iIwCEDLwR0DqDbCO4DP+KRqkhw+vD0YuG4QvXeQ13AA=,tag:WIJ7khz1UX54cFXSVHWP4w==,type:str]
    version: 3.13.3
