apiVersion: v1
kind: Secret
metadata:
    name: minio-secrets
    namespace: flux-system
type: Opaque
stringData:
    MINIO_ADMIN_PASSWORD: ENC[AES256_GCM,data:Rxe/4C7dLwPZComifnggdI7iXNWGh5P9itZkACyKgEa948yvGXInu2OgIG8M3PFh,iv:SqiJclK2gYJjzH+x8lHivu7sWTWWrq6BZ/23NEQNVds=,tag:WAYp/Z0TCgHsF6YjNON9JQ==,type:str]
    MINIO_ADMIN_USER: ENC[AES256_GCM,data:wUqN0rhEn03Dzg==,iv:UqIQqNpO5nGjI5dhUQ8/giGCi5ZjPdkLxxgYohgzl+Y=,tag:QsNtbZqRSwrqc2gVFdA7Ug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOWg5Q1p6RlJTM2duRmxU
            TGMzOXJIaVRPbTFETUErR1J0TDFzS2pRN1NjClpXMm9LYWVGcDU1dnZWVjBHR21Y
            QkJMaUpWUTg0b2E3N1Y2K3BUbHJFUmcKLS0tIHZoZFZ4UGx1eDlMK2QvcnJUSWVr
            VktGcW83M0FvUmZPSk5md2RoNnEyNmsK/2QTPL3OzqKnLhMy81JCDTuP6o8HeaEQ
            GzEE1GCQsPvr/lk3vBO+I74Dw2V3UFgvLkL1kynnZvgHvySyOEXzZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n5eqcd3nhuqmvg2h02c0wl2mpyx7tm62payw6ed2txnf7aevp9wq9wxue3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSkhvekwycWFHMmhUUTRy
            VFdZalJ2NHlUWmRuaklvYU9jY0Yrc0FtV1VVCjRsdjljbnQrYTdIQ2wvcVdLQUdK
            dDZrRHRWWFJlSVBxMjR1RjZYQjY2MjAKLS0tIFNydXgvSnp1ZUkwVFUrUFJNWDBv
            T3crUTJQSXJXdlNXdXhLdmxIc3NLQUkKQOjXeRRqEcNJYisRXT0ecx5Kx/TziTtj
            z1Dgs0xgpRWfJM/9G4+1l8n1ePzvA6RuoO97hjs/SDrLKzgf0F/iLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T05:08:07Z"
    mac: ENC[AES256_GCM,data:VmXRXNQBPP8v4LgV0bCDvcQuTFVBQkOPDcrkp6iBETBKZVpyiY9QKS84OKYbp30ifVb4XmPHQGS0PGUbzOIbUn7WVHRJD4tDOU/tgpr2L06bbaYaNFgTvR6L4fx/xaLUo78dpkKfzp5DQDbEvnKR+Ibf8DdvAM3ODXa9f6/8o5Q=,iv:Z6t7CEtcZ5pQ8sMx/Olzb2HX90Y+zhbuUv3riy3JmIM=,tag:vzvr85ufgIyVJoMKI62P8A==,type:str]
    version: 3.13.3
