apiVersion: v1
kind: Secret
metadata:
    name: openbao-sops-secrets
    namespace: flux-system
type: Opaque
stringData:
    OPENBAO_ADMIN_PASSWORD: ENC[AES256_GCM,data:0Jl9ysJ5myNgP6bnzhWru4XfntVgTjH97MsRJ7mhEoI=,iv:ROTgjqiYu8vPMxXTXjMb0jqCrlsaRanAsQQzGcAR3aw=,tag:daxBgw2Xu8RadooFv94/1A==,type:str]
    OPENBAO_SEAL_STATIC_KEY: ENC[AES256_GCM,data:Kqj8aEjJJA7dlVUh3XukhlFchkU18veo7VWzJevNdSxZjaTkH5vIaVf1DpM=,iv:k23D1iwOCx8A53yQEAImcLsHpj72rw/FcJpzrYvb4V0=,tag:nTbdvqpncmZPBHK+xVsxCw==,type:str]
    OPENBAO_TERRAFORM_PASSWORD: ENC[AES256_GCM,data:VcFv0yG4B4iNKdJxoD7c1WlA7LffdjYndTonjxS7j0w=,iv:A661GaL2N31endSDf8z7ycWOmwrlBL4fU2VPhY/Zb0k=,tag:7JHjtU/z2xRHJv1xI11NwQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Y1lyaXJ6Z2VicU5ybGZx
            NGw0WTNJcXF2ZWNIL0Z2SWZEMWdFNUhNUWtBCjE1elJYUkFlNlpobTdhSXVlNVhI
            RVM2bVJIaTh3MWRGZjBuaWx5cng5Z3MKLS0tIFh4dzluVWRTcldPbUtJaldLRXQ1
            RUIraG5NeElqaHRwSzlmdVNFUFhpemMKmTUCPb5FppZ5g5ejQCfvjWjANJyxvVYO
            GJJX26wjB2xzQM1sE2tYweSxTxjhaDURnKg1/kWsU0KTbPJr5lssDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n5eqcd3nhuqmvg2h02c0wl2mpyx7tm62payw6ed2txnf7aevp9wq9wxue3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRGRYK2swQ0JrS1VCc3lW
            SURqSVJDb25qYlZJSjBvemQxYjhzT1gyVlZBCkhrUmQycXR5UWp6MldlbnhLdExX
            YmliMzlnOFhFVHRSNzZ3clM1ZmpaSVkKLS0tIDVJR0RHZTVqQm9uMUxEUXVCbk1V
            aDZOTG10Z09hRk5PL2MraHlsNUR4N28KNmcLpyFWQhgaGEl2U4fuPuFFo3O1G/wi
            W7ImcZeO85tL2Tp/hqn1r188nOaqG6GUNBfij37gvMs5wxZ8Cbdvow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T14:31:24Z"
    mac: ENC[AES256_GCM,data:ZVxb/ewPtSeTeZHJQ7OvhRgXWzN90lGQOHnVNUeIm4ae8AL5iAryteTqI+Ztuu4pJVT3f420/SvUlIaFNYGk33MNsQb0CzRQ/09ay5hvgzyKF8+Zodz0POjE8ph46lD3g02SzZE/VGr3bbn4/u2iTvTr+jYZdC7qEFXv/hz0xE0=,iv:I28VD6Raq9ejDJp5c/gRn79rT7e/KeabDrfAnYmZnAs=,tag:oFqsb1+WCZejEbmIXe+ChA==,type:str]
    version: 3.13.3
