apiVersion: v1
kind: Secret
metadata:
    name: openbao-sops-secrets
    namespace: flux-system
type: Opaque
stringData:
    OPENBAO_SEAL_STATIC_KEY: ENC[AES256_GCM,data:Xx2GGtXXOuQ5W1kZeclBDHNCJK6YcAoLQJXOuYlrwL9Xs8ysMbzWg5khZvA=,iv:CziOQlggnPE/S8XOTHAOfBSc41/IpPWqjj09lnDwdnU=,tag:b1PdPwVA1Q7Hd2r/jx3DkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOGFYUXhYeSszOEV6dGFq
            TkVYQktWZVBiQTFSUVJmMWptaUtSWUlrU0RvCjRGRGN0YUxBMFc2Sm4vRmNDKy84
            L0tYc2x6YXFqdHZvWXJWcWlDc3VXVncKLS0tIDRZc1RBWlNBelNSZHliQ3ZPQTUw
            UkNjdGFTNVRKYnIyblJQVkd5SXFQbEEKN0w5Omfjo690ozCC7ZzIGCdrmtost18h
            3mzqb5HYLmDBkEBSZZ0rcqO1WmgS+gwHGuwhCHWg+566/5PUv6fNXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n5eqcd3nhuqmvg2h02c0wl2mpyx7tm62payw6ed2txnf7aevp9wq9wxue3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbTFXTnJzcjFXSGwrb1Zr
            dmI3Mk9sRzdBamdFdnlzYkhwd0NGbGZjeUhvCmIwNS9QOUZjODZpR0s1UC82eWJq
            MklsQWtBeTJVdzVkU2diRzlPY1hmQ00KLS0tIG81OHZWaTFtK2N1SDBIOWpXb25S
            eE9jQm5kbnBQeU1qNGVxZUxJR1NlQTQKMGejGuHte3lhT2IPXS6DdcL87aM3jgWg
            EvA1XJLHG/7XSvByl+ehj952e7RGoe+rQCv5RbxJftxfJbHdvJz5Dg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T05:08:08Z"
    mac: ENC[AES256_GCM,data:ZXMxayOYgGVrOD3zWjlOMbKhS3tXIsINQnTg6czqAA3OXnwuOI6kRW9G4bPcsmFneBrFAt07KqcUv1LJVf5Dc3dUCfINvKW9FSG/IpbDBfdPC5gvBk+EMndtHfQOse7lV49C0WmJjyyhYKhaq1CbV3UU65a7E9C/e4qHcgGzBAE=,iv:RIiG7uGl2ZPxQ+FdCd2YYAjzGV382l02bKU/m/mp4cc=,tag:xYp1uA06SgMM0TqaGvLgdg==,type:str]
    version: 3.13.3
