apiVersion: v1
kind: Secret
metadata:
    name: tabletennis-sops-secrets
    namespace: flux-system
type: Opaque
stringData:
    SCHMETTERPAUSE_BACKUP_ACCESS_KEY_ID: ENC[AES256_GCM,data:tjuFNmMYkpHlduw8Dd2d2CbTHg==,iv:qebWB9lnzWee57JRNSQWDUvXlmZ2abNb4flIf5h7QT8=,tag:6sMp3mT88Jyi+TffZ0wwRQ==,type:str]
    SCHMETTERPAUSE_BACKUP_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:bXIcdR0VuB58A5Nfz/gVR0z4XCPrK2ulfO4npNrakxHLBKxYut1qY6SC+uPHe9nX,iv:DE51wDGsputZL7zguoio/miwpaNS+KHSJcwveNUXkbM=,tag:LmzprSgNqxvsYdhtCE16Mw==,type:str]
    SCHMETTERPAUSE_DB_PASSWORD: ENC[AES256_GCM,data:NSheetpRKgAgXA7jBrned/bIQNZvzogSH+y5p5q8aeDdClP867EnJg5RNGs59uHD,iv:ZTtMMtJWaGcH/pSm4AXWgoADCEJBPGeABiXbrBaS1JQ=,tag:DfyrIsHiGbLhSo7/5dtPMg==,type:str]
    SCHMETTERPAUSE_SESSION_KEY: ENC[AES256_GCM,data:Em7nZyTpsu625iIhiQIKZfESAxcn2REdDiHo/qLDcW4EELwsNRGuU52YUnnGw1PhB6NI78poFlIsagm860/QHQ==,iv:pLk3T4rud9oxwsWS5s/KLd9q6KYgfCEu/KzoeY3d9ts=,tag:N2wEYfh581KGPQLpro/PYw==,type:str]
    ZAEHLWERK_OMNI_PITCHER_TOKEN: ENC[AES256_GCM,data:vwKanz+rHO3LppdxXpCEcUTv37GIG6TwoMHKqur+WhaEQc2IQts9xaw2mO+s/n/K,iv:e7AkBepgjQ//U7qeW6tILUDjeucG+ACimfgAwraGjYs=,tag:7dnUCEFas+keRcdxMqHYbw==,type:str]
    ZAEHLWERK_REDIS_PASSWORD: ENC[AES256_GCM,data:70fVve0g5WsPP5OOI/Lqx1wVlPpla3xeI6FjXQrhRocO9jf6C4Ia1Rl4Qw8Vc2Zv,iv:v1rrSPyzj1i53pPb2Wm79W76eptVuuAkkbN3wLBzLh8=,tag:a7iD4VXMPWRKx75RzQnobw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWTNadDc1Y0xYSGY2RzEv
            TFc4WkhCQmxBZWw5TExjaWhxcUh5OXB0TFJnCkJha1dLTGRxcG13LzQ4YnpkYS84
            UWFTMEVEaDBSUzBtby81NE1LNHVucXMKLS0tIHFUUUdwaFdNblR5d0JHcm5qUGUx
            YlMrVHNRYXBzWTZEdThQS2ZxU1FaajQKOIPatXBb353MQ+bvZTXIDLytzGl0WlcA
            V7gfsvMoqpiOWQPtIR4AqhGbM5zukdawLJPoDutl8z5ElMf63rxmLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n5eqcd3nhuqmvg2h02c0wl2mpyx7tm62payw6ed2txnf7aevp9wq9wxue3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuaWRoWkhoOWlGcisxVnNF
            SXY4RXNOeG8yRVJqS1FPVkI2MHY5Y1ZEdUZBCkhwRG1UQVBGYVZ1ZjNoaUNaOGhX
            RG40QmhyOWlFcWZjaFBEbkhOUFVYajAKLS0tIDVNUUloL0YzdE55MWJHa2taeVlV
            WXdjYWVYcmlXd0dWd3NuSERtWWJyT2sKyz5eyyi9tXbLvcaAJ2R/Cy6VJNopmMjO
            dddzNGnUyZY5vD0SzvIBJ4DCy/JQ0nc7fnz8KfmCiRAAWG5gHkz1yg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T05:08:08Z"
    mac: ENC[AES256_GCM,data:tnRs1km58ERyl2VDgM2xvbRIZS4GT7NidVlhr5h6Q1blJ6ic5ol3URh0mEzyIXflW/2Xi8p1oXps++n4NCVYOjT/LD4oK93uPvvqzj3jzZG/DulQz651HMPl8lAgYRaViRbyPPWAgllRyEb28IQLNkAp0UyWwtaJllwJ7qJwAJ4=,iv:4wAotxrlX0FV/u67ELfj3+/d0YeMUBDWLXL05txpXOo=,tag:LBroOBD6NwkC3kDW3V27lw==,type:str]
    version: 3.13.3
