apiVersion: v1
kind: Secret
metadata:
    name: tabletennis-sops-secrets
    namespace: flux-system
type: Opaque
stringData:
    SCHMETTERPAUSE_BACKUP_ACCESS_KEY_ID: ENC[AES256_GCM,data:QSbKskuy8d8Fdq2C3/QsOplx6Q==,iv:ZjX02mOKJluLjG240Vk/s88eXxL4DNz+vuEeo/v1DEU=,tag:0MbYabRJb3rLSlmiK7IhCQ==,type:str]
    SCHMETTERPAUSE_BACKUP_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BCJ68gmv0AycMA17rnR6wVJShRPVBi5Dpkp5kTOSy43y1fe2gXzdxGjpiiZo4pMp,iv:n2YMj+29JugiHHqPPXM6sFu/SSrD4kNQbbCyVRDBQ6g=,tag:b5yjplScZDnGPSVbVKeEbw==,type:str]
    SCHMETTERPAUSE_DB_PASSWORD: ENC[AES256_GCM,data:2S+i4d+E+lseRzdWQDHXRj+pG4yhlSZ+EOHeDHgDRpn87vGoPB+TLLde4juk0ItK,iv:G3hH7q74groBACD/TJqSXoHvuKGxD8UW8YplFYLd2T4=,tag:L85WKPmJDLNs3TI43samGw==,type:str]
    SCHMETTERPAUSE_SCOREBOARD_TOKEN: ENC[AES256_GCM,data:8VNZ4KbUt4nXEG0Ztyzn+YdPDGrLRCBKvrsHEnWXGBhGWj5NX7IGz3X/rMJbjLQQrnFGplpVdVeR3LuX297sRw==,iv:LBYKrTNeRmick0qono31c5TGjWvLOWRY85RynovumMQ=,tag:gKigmWeWzf0znElJJhKL8w==,type:str]
    SCHMETTERPAUSE_SESSION_KEY: ENC[AES256_GCM,data:U/sgMGkuvVgAh3xhtKmWZ6e8OLVSgoK9+iqB/Y+4Vdn0KteYfsA/2FcedW8Xex+KwdyKIOsYsm/keU49hIEq+Q==,iv:pPFqChLPR+ymh4aGQwQln/SgtWsALQa3Cb6AjPUZZ8g=,tag:u/HePzHQ2Tsmx+BOuA5gLQ==,type:str]
    ZAEHLWERK_OMNI_PITCHER_TOKEN: ENC[AES256_GCM,data:2axEkbvv3qv6ggWkHCkIoVdCe401mMo4B1HSxS9JH981YTXevnSnin+u1V8if08f,iv:XeKa5PZdqwssipy5/3QK0c4gBq/AloamMLikvkqhBVw=,tag:dr3LhC28QcJPb7iVQV/pvA==,type:str]
    ZAEHLWERK_REDIS_PASSWORD: ENC[AES256_GCM,data:YmptbIdWVt6PULw8fxh8+wGsM/TE/zsEYzPKvteiAzk8dEHCgMh1FG5saV1HG2F8,iv:gbOEIFN/J3t75BS2IUX2cHXm2jLLXzlaWiVex6Um/Zk=,tag:LqX9HEJ6BQ9uB6DJFPaavw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bVBoWW9QMXV5U2ZSeGlI
            aTY4dHZoQjZIMkFWNnd5b3dFNVRoeTlhUnl3CjVRWDJsK2JucXhtMUdweGpXc090
            Skh2N3UvTGpCWnlnODk4NnpZMTQ0TncKLS0tIHRmeU80RWJPVE9XdUZuaEhRQmNR
            Yi9Ubjh3SEJYZmJlamxWN3ZNN0IvdnMKx3IFezQw85+2tYHx4F/US8M2ZHlaVb7c
            Uusybk2PCsY8iDArdizFfmW1oFDt9fvzGSHG72oMd4A0qY46VTo3zg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n5eqcd3nhuqmvg2h02c0wl2mpyx7tm62payw6ed2txnf7aevp9wq9wxue3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFc0RrSnVNbEhSRXVrRGFM
            VTdWRkZJVnlxVW5NK1ZVc0FCRjQxSFAza1ZvCjdyYnoreFd4ZVJGQXFqS28rOUw4
            aHI1aGRUNDExM2RiVVp6R2pDQnpmRUkKLS0tIEtVRFpnc3VsRzBBWHcxaUoyOHlq
            NXhmYW0xaGZiRERCcHZRS1h0YUEzRTgKPzTGHq0UrKtMQCE1yDFDYIcndynXhj9S
            t23Gqe8MFN4Y8y+Y81iO83v4p7UyyaWGDdC7JuAMgOdUcpc9dtz1Jw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19vgzvmpt9tdlcsu8rzaacj397yz8gguz38nsmuy6eeelt5vjsyms542xtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T14:20:32Z"
    mac: ENC[AES256_GCM,data:rvmXgTuj9XrVPCSSJ1/xJmuEQdP3hOJt9Nns8PB3171F9jxqLHNzxoXYYdsUwvLU/OfwBIVQrCpAYtNuLr1qnz+9h+neqpz4ztN5Bywoj3BKpixW487Qok1azQS7heFaOEBFwsMOy4ncGUXEEliF/+37E/o8nCWZmMjrI5VxXeQ=,iv:REhvjXy3ipZDNFk1K+xfhkZeR7HzwU7FIQC7pZgAWvg=,tag:BN/BKZ+5f26Jz3fnHSPh9g==,type:str]
    version: 3.13.3
